Update ABI Auto Detect.yml

diff --git a/.github/workflows/ABI Auto Detect.yml b/.github/workflows/ABI Auto Detect.yml
--- a/.github/workflows/ABI Auto Detect.yml
+++ b/.github/workflows/ABI Auto Detect.yml
@@ -1055,10 +1055,9 @@ jobs:
           kill -TERM $PROGRESS_PID >/dev/null 2>&1 || true
           wait $PROGRESS_PID 2>/dev/null || true
           
-            if [[ $SYNC_STATUS -ne 0 ]]; then
-              echo "⚠️ Repository Sync Failed After Retry"
-              exit 1
-            fi
+          if [[ $SYNC_STATUS -ne 0 ]]; then
+            echo "⚠️ Repository Sync Failed After Retry"
+            exit 1
           fi
       
           echo "🔎 Detecting Kernel Repository..."
