Update ABI Auto Detect.yml

diff --git a/.github/workflows/ABI Auto Detect.yml b/.github/workflows/ABI Auto Detect.yml
--- a/.github/workflows/ABI Auto Detect.yml
+++ b/.github/workflows/ABI Auto Detect.yml
@@ -3002,12 +3002,24 @@ jobs:
           echo "------------------------------"
           echo ""
           
-          # Directories
-          KERNELDIRECTORY="kernel_workspace/kernel_platform/common"
+          # Automatically Detect the Kernel Directory by Searching for Sched Headers
+            echo "🔍 Searching for sched.h to automatically detect the kernel directory..."
+            KERNELDIRECTORY=$(find . -type f -name "sched.h" -exec dirname {} \; | head -n 1)
+
+            if [ -z "$KERNELDIRECTORY" ]; then
+              echo "⚠️ Could Not Find Sched Headers, Ensure that the Kernel Source is Checked Out Correctly..."
+              exit 1
+            fi
+
+          # Set the Path for Sched Headers
           SCHEDH="$KERNELDIRECTORY/include/linux/sched.h"
 
-          # Move to Kernel Directory
-          cd "$KERNELDIRECTORY"
+          # Debugging step: Check if the sched.h file exists
+          echo "🔍 Checking if Sched Headers Exists at $SCHEDH"
+          ls -l "$SCHEDH" || { echo "⚠️ Sched Headers File Not Found at $SCHEDH"; exit 1; }
+          
+          # Navigate to the Kernel Directory
+          cd "$KERNELDIRECTORY"       
           
           echo "🔧 Starting DroidSpacesLXC Auto-Patch..."
           echo "📄 Target: $SCHEDH"
