Update AOSP LOS CRD SM8750.yml

diff --git a/.github/workflows/AOSP LOS CRD SM8750.yml b/.github/workflows/AOSP LOS CRD SM8750.yml
--- a/.github/workflows/AOSP LOS CRD SM8750.yml
+++ b/.github/workflows/AOSP LOS CRD SM8750.yml
@@ -476,6 +476,30 @@ jobs:
           fi
 
 
+      - name: 🗂️ Setup Reject Checker
+        shell: bash
+        run: |
+          # Define Reject Checker
+          REJECTCHECKER="${WORKDIR}/AndreiMikh-Kernel-Lab/scripts/RejectChecker.sh"
+
+          # Validate Reject Checker
+          if [[ ! -f "$REJECTCHECKER" ]]; then
+            echo "⚠️ Reject Checker Not Found:"
+            echo "$REJECTCHECKER"
+            exit 1
+          fi
+
+          # Make Reject Checker Executable
+          chmod +x "$REJECTCHECKER"
+
+          # Export Reject Checker
+          echo "REJECTCHECKER=$REJECTCHECKER" >> "$GITHUB_ENV"
+
+          echo
+          echo "🔎 Reject Checker: $REJECTCHECKER"
+          echo "🎉 Reject Checker Ready"
+
+
       - name: 📂 Prepare Kernel Sources
         if: ${{ inputs.aospsource == 'Lineage' || inputs.aospsource == 'CrDroid' }}
         shell: bash
@@ -1130,6 +1154,10 @@ jobs:
             exit 1
           fi
 
+          # Load Reject Checker
+          source "$REJECTCHECKER"
+          checkrejects .
+
           # Display SUSFS Result
           echo
           echo "🎉 SUSFS Integration Complete"
@@ -1165,6 +1193,10 @@ jobs:
           bash "$SCRIPT"
           echo "✔️ LZ4 Update Script Completed"
 
+          # Load Reject Checker
+          source "$REJECTCHECKER"
+          checkrejects .
+
           # Display LZ4 Result
           echo "🎉 LZ4 1.10.0 + Neon Patch Update Completed"
           echo "📂 Kernel Source : ${SOURCEDIR}"
@@ -1188,7 +1220,6 @@ jobs:
           git clone --depth=1 \
             https://github.com/GuLingguang/oneplus-sm8750-kernel-pro-build.git \
             "${GITHUB_WORKSPACE}/extra-files"
-
           if [ "${{ inputs.droidspaces }}" = "false" ]; then
             echo "🚫 DroidSpaces Disabled"
             exit 0
@@ -1197,15 +1228,11 @@ jobs:
           echo "📦 Installing DroidSpaces Sources..."
           cp -f "$EXTRA/drivers/misc/ntsync.c" \
             "$SOURCEDIR/drivers/misc/"
-
           cp -f "$EXTRA/include/uapi/linux/ntsync.h" \
             "$SOURCEDIR/include/uapi/linux/"
-
           rm -rf "$SOURCEDIR/drivers/gpu/drm/evdi"
-
           cp -r "$EXTRA/drivers/gpu/drm/evdi" \
             "$SOURCEDIR/drivers/gpu/drm/"
-
           echo "✔️ DroidSpaces Sources Installed"
 
           for FILE in \
@@ -1261,11 +1288,9 @@ jobs:
           if ! grep -qF 'ANDROID_KABI_USE(6, struct sysv_sem sysvsem);' "$SCHEDFILE"; then
             grep -qF 'struct sysv_sem			sysvsem;' "$SCHEDFILE" || exit 1
             grep -qF 'struct sysv_shm			sysvshm;' "$SCHEDFILE" || exit 1
-
             perl -0pi -e \
               's/\tstruct sysv_sem\s+sysvsem;\n\tstruct sysv_shm\s+sysvshm;/\t\/\/ struct sysv_sem\t\t\tsysvsem;\n\t\/\/ struct sysv_shm\t\t\tsysvshm;/' \
               "$SCHEDFILE"
-
             perl -0pi -e \
               's/\tANDROID_KABI_RESERVE\(6\);\n\tANDROID_KABI_RESERVE\(7\);\n\tANDROID_KABI_RESERVE\(8\);/\t#ifdef CONFIG_SYSVIPC\n\tANDROID_KABI_USE(6, struct sysv_sem sysvsem);\n\t_ANDROID_KABI_REPLACE(ANDROID_KABI_RESERVE(7); ANDROID_KABI_RESERVE(8), struct sysv_shm sysvshm);\n#else\n\tANDROID_KABI_RESERVE(6);\n\tANDROID_KABI_RESERVE(7);\n\tANDROID_KABI_RESERVE(8);\n#endif/' \
               "$SCHEDFILE"
@@ -1276,15 +1301,12 @@ jobs:
             perl -0pi -e \
               's/(#include <uapi\/linux\/pidfd\.h>\n)/$1#include <linux\/version.h>\n#include <linux\/refcount.h>\n#include <linux\/module.h>\n/' \
               "$PIDFILE"
-
             perl -0pi -e \
               's/(EXPORT_SYMBOL_GPL\(init_pid_ns\);\n)/$1\nstatic struct task_struct ghost_task;\nstatic bool ghost_task_ready;\n\n#define set_task_usage(target, value) _Generic((target), refcount_t: refcount_set, atomic_t: atomic_set)(&(target), (value))\n\nvoid __init init_ghost_task(void)\n{\n\tmemcpy(\&ghost_task, \&init_task, sizeof(struct task_struct));\n\tstrncpy(ghost_task.comm, "ghost-task-sentinel", TASK_COMM_LEN);\n\tghost_task.pid = -1;\n\tghost_task.tgid = -1;\n\tset_task_usage(ghost_task.usage, 1000);\n#ifdef CONFIG_REFCOUNT_FULL\n\trefcount_set(\&ghost_task.refcount, 1000);\n#endif\n\tghost_task_ready = true;\n}\n/' \
               "$PIDFILE"
-
             perl -0pi -e \
               's/\treturn find_task_by_pid_ns\(vnr, task_active_pid_ns\(current\)\);/\tstruct task_struct *task;\n\tstruct module *mod;\n\tunsigned long caller_ip = _RET_IP_;\n\n\ttask = find_task_by_pid_ns(vnr, task_active_pid_ns(current));\n\tif (unlikely(!task)) {\n\t\tpreempt_disable();\n\t\tmod = __module_address(caller_ip);\n\t\tif (mod \&\& strcmp(mod->name, "oplus_bsp_midas") == 0) {\n\t\t\tpreempt_enable();\n\t\t\treturn ghost_task_ready ? \&ghost_task : \&init_task;\n\t\t}\n\t\tpreempt_enable();\n\t}\n\treturn task;/' \
               "$PIDFILE"
-
             perl -0pi -e \
               's/(void __init pid_idr_init\(void\)\n\{\n)/$1\tinit_ghost_task();\n/' \
               "$PIDFILE"
