Update AOSP.yml

diff --git a/.github/workflows/AOSP.yml b/.github/workflows/AOSP.yml
--- a/.github/workflows/AOSP.yml
+++ b/.github/workflows/AOSP.yml
@@ -66,14 +66,14 @@ jobs:
         sed -i '$a CONFIG_KSU_SUSFS=y' $GITHUB_WORKSPACE/kernel_workspace/sm8750/arch/arm64/configs/vendor/oplus/sun_perf.config
 
 
-    - name: Setup Pershoot KernelSU-Next
+    - name: Setup KernelSU-Next
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/sm8750
 
         if [[ ${{ github.event.inputs.ksu_type }} == "ksunext" ]]; then
           echo "Configuring KernelSU Next..."
          
-          curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/dev-susfs/kernel/setup.sh" | bash -s dev-susfs
+          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/dev/kernel/setup.sh" | bash -s dev
           cd KernelSU-Next
         
           KSU_VERSION=$(expr $(curl -sI "https://api.github.com/repos/pershoot/KernelSU-Next/commits?sha=dev&per_page=1" | grep -i "link:" | sed -n 's/.*page=\([0-9]*\)>; rel="last".*/\1/p') "+" 30000)
@@ -118,24 +118,27 @@ jobs:
           git clone https://github.com/Liam314839/wildpatches
          
           echo "Applying WildKernels Patches..."
-          for patch in wildpatches/*.patch; do
-            echo "Applying $patch"
-            patch -p1 < "$patch" || true
-          done
 
+          if patch -p1 < "$patch"; then
+            echo "Applied: $patch"
+          else
+            echo "WARNING: Failed Patch -> $patch"
+          fi
+       
           echo "Wild Kernels Patches Applied Successfully"
 
     - name: KernelSU and SUSFS Configurations
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/sm8750
 
-        echo "Enabling KernelSU + SUSFS config..."
+        echo "Enabling KernelSU + SUSFS Configurations..."
 
         CONFIG_FILE="arch/arm64/configs/vendor/oplus/sun_perf.config"
 
         grep -q "CONFIG_KSU=y" $CONFIG_FILE || echo "CONFIG_KSU=y" >> $CONFIG_FILE
         grep -q "CONFIG_KSU_SUSFS=y" $CONFIG_FILE || echo "CONFIG_KSU_SUSFS=y" >> $CONFIG_FILE
-
+        grep -q "CONFIG_KSU_SPOOF=y" $CONFIG_FILE || echo "CONFIG_KSU_SPOOF=y" >> $CONFIG_FILE
+       
         echo "Config Updated:"
         tail -n 10 $CONFIG_FILE
    
