Update AOSP LineageOS.yml

diff --git a/.github/workflows/AOSP LineageOS.yml b/.github/workflows/AOSP LineageOS.yml
--- a/.github/workflows/AOSP LineageOS.yml
+++ b/.github/workflows/AOSP LineageOS.yml
@@ -73,7 +73,7 @@ jobs:
 
         mkdir -p common/arch/arm64/boot/dts
         cp -r sm8750-dt/arch/arm64/boot/dts/* common/arch/arm64/boot/dts/
-
+   
     - name: Inject Kernel Configurations
       run: |
         CONFIG="kernel_workspace/common/arch/arm64/configs/vendor/oplus/sun_perf.config"
@@ -90,19 +90,14 @@ jobs:
 
           echo "Installing KernelSU-Next..."
 
-          curl -LSs https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/dev/kernel/setup.sh | bash -s dev || true
+          rm -rf KernelSU-Next
 
-          if [ ! -f KernelSU-Next/kernel/Kbuild ]; then
-            echo "KernelSU Incomplete, Cloning Fallback..."
-            rm -rf KernelSU-Next
-            git clone https://github.com/pershoot/KernelSU-Next -b dev-susfs KernelSU-Next
-          fi
-        
+          git clone https://github.com/KernelSU-Next/KernelSU-Next -b dev KernelSU-Next
+ 
           cd KernelSU-Next
 
-          # Sanity Check
-          if [ ! -f "kernel/Makefile" ] && [ ! -f "kernel/Kbuild" ]; then
-            echo "KernelSU-Next Appears Incomplete"
+          if [ ! -f kernel/Kbuild ] && [ ! -f kernel/Makefile ]; then
+            echo "KernelSU tree invalid"
             exit 1
           fi
 
@@ -110,7 +105,7 @@ jobs:
           echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
 
         else
-          echo "KernelSU disabled"
+          echo "KernelSU Disabled"
         fi
 
     - name: Setup SUSFS
@@ -120,19 +115,15 @@ jobs:
         git clone --depth=1 -b gki-android15-6.6 \
           https://gitlab.com/simonpunk/susfs4ksu.git
 
-        cp susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch KernelSU-Next/
-        cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-android15-6.6.patch .
-
         mkdir -p fs include/linux
-        cp -r susfs4ksu/kernel_patches/fs/* fs/ || true
-        cp -r susfs4ksu/kernel_patches/include/linux/* include/linux/ || true
 
-        cd KernelSU-Next
-        patch -p1 --forward --ignore-whitespace < 10_enable_susfs_for_ksu.patch || true
+        cp -r susfs4ksu/kernel_patches/fs/* fs/
+        cp -r susfs4ksu/kernel_patches/include/linux/* include/linux/
 
-        cd ..
-        patch -p1 --forward --ignore-whitespace < 50_add_susfs_in_gki-android15-6.6.patch || true
-
+        # Kernel Patch
+        patch -p1 --forward --ignore-whitespace \
+          < susfs4ksu/kernel_patches/50_add_susfs_in_gki-android15-6.6.patch || true
+  
     - name: Wild Patches
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/common
