Update Dodge Lineage Kernel Build.yml

diff --git a/.github/workflows/Dodge Lineage Kernel Build.yml b/.github/workflows/Dodge Lineage Kernel Build.yml
--- a/.github/workflows/Dodge Lineage Kernel Build.yml
+++ b/.github/workflows/Dodge Lineage Kernel Build.yml
@@ -512,27 +512,45 @@ jobs:
     # =========================
     # Kernel Configuration
     # =========================
-    - name: 🔧 Kernel Configuration
-      run: |
+    - name: Kernel Configuration
+      env:
+        SUSFS: ${{ github.event.inputs.SUSFS }}
+        KSU: ${{ github.event.inputs.KSU }}
+      run: |    
         cd "$WORKSPACE/$KDIR"
-        
-        # Set the Path to the Configuration File
+
+        # Config
         CONFIG="$WORKSPACE/$KDIR/arch/arm64/configs/vendor/oplus/sun_perf.config"
-
-        # Get Github Environment Variables and GitHub Actions Inputs    
-        SUSFS="${{ github.event.inputs.SUSFS }}"
-
+    
+        # Ensure Config Exists
+        if [[ ! -f "$CONFIG" ]]; then
+          echo "⚠️ Config File Not Found: $CONFIG"
+          exit 1
+        fi
+    
+        # Ensure Newline
+        echo "" >> "$CONFIG"
+    
         # KSU Config
-        echo "CONFIG_KSU=y" >> "$CONFIG"
-
+        if [[ "$KSU" != "None" && -n "$KSU" ]]; then
+          echo "CONFIG_KSU=y" >> "$CONFIG"
+          echo "🎉 KSU Config Applied"
+        else
+          echo "⚠️ KSU Config Not Applied"
+        fi
+    
         # SUSFS Config
         if [[ "$SUSFS" == "SUSFS-GKI" || "$SUSFS" == "SUSFS-OKI" ]]; then
           echo "CONFIG_KSU_SUSFS=y" >> "$CONFIG"
+          echo "🎉 SUSFS Config Applied"
+        else
+          echo "⚠️ SUSFS Config Not Applied"
         fi
-
+    
         # FS Config
         echo "CONFIG_TMPFS_POSIX_ACL=y" >> "$CONFIG"
-        echo "CONFIG_TMPFS_XATTR=y" >> "$CONFIG"      
+        echo "CONFIG_TMPFS_XATTR=y" >> "$CONFIG"
+        echo "🎉 FS Config Applied"
    
     # =========================
     # Build Kernel
