Update Dodge Lineage Kernel Build.yml

diff --git a/.github/workflows/Dodge Lineage Kernel Build.yml b/.github/workflows/Dodge Lineage Kernel Build.yml
--- a/.github/workflows/Dodge Lineage Kernel Build.yml
+++ b/.github/workflows/Dodge Lineage Kernel Build.yml
@@ -67,6 +67,39 @@ jobs:
         echo "BUILDTIME=$(date '+%y%m%d')" >> $GITHUB_ENV
 
     # =========================
+    # Repository Tool
+    # =========================
+    - name: Repository Tool
+      shell: bash
+      run: |    
+        BIN="/usr/local/bin/repo"
+        GOOGLE="https://storage.googleapis.com/git-repo-downloads/repo"
+        GITHUB="https://raw.githubusercontent.com/GerritCodeReview/git-repo/main/repo"
+    
+        echo "🚀 Checking Repository Tool Installation..."
+    
+        if command -v repo &>/dev/null; then
+          echo "🎉 Repository Already Installed"
+        else
+          download() {
+            curl -fL --retry 3 --retry-delay 5 "$1" -o repo
+          }
+    
+          echo "🚀 Installing Repository Tool..."
+    
+          if ! download "$GOOGLE"; then
+            echo "⚠️ Google Failed, Trying GitHub..."
+            download "$GITHUB"
+          fi
+    
+          chmod +x repo
+          sudo mv repo "$BIN"
+        fi
+    
+        repo --version
+        echo "🎉 Google Repository Ready"
+
+    # =========================
     # Cache CCache
     # =========================
     - name: Cache CCache
@@ -86,6 +119,24 @@ jobs:
       with:
         path: ${{ env.WORKSPACE }}/clang-aosp
         key: ${{ env.CLANG_VERSION }}
+
+    # =========================
+    # Configure Git Identity
+    # =========================
+    - name: 🔧 Configure Git Identity
+      shell: bash
+      run: |
+          if ! git config --global user.name >/dev/null; then
+            git config --global user.name "AndreiMikh"
+          fi
+          
+          if ! git config --global user.email >/dev/null; then
+            git config --global user.email "andreimikhail0088@gmail.com"
+          fi
+
+          echo ""
+          echo "🎉 Git Configuration Applied:"
+          git config --global --list
 
     # =========================
     # Download Clang Toolchain
@@ -461,7 +512,7 @@ jobs:
         # KSU Handling
         echo "🔧 Checking KSU Support..."
         
-        if grep -q "CONFIG_KSU" out/.config; then
+        if grep -q "^CONFIG_KSU=y" out/.config; then
           echo "🎉 KSU Supported"
           $CONFIGTOOL --file out/.config -e CONFIG_KSU
         else
@@ -472,7 +523,7 @@ jobs:
         if [ "${{ github.event.inputs.SUSFS }}" = "SUSFS-GKI" ] || [ "${{ github.event.inputs.SUSFS }}" = "SUSFS-OKI" ]; then
           echo "🔧 Checking SUSFS Support..."
         
-          if grep -q "CONFIG_KSU_SUSFS" out/.config || grep -q "CONFIG_SUSFS" out/.config; then
+          if grep -q "^CONFIG_KSU_SUSFS=y" out/.config || grep -q "^CONFIG_SUSFS=y" out/.config; then
             echo "🎉 SUSFS Supported"
             
             if grep -q "CONFIG_KSU_SUSFS" out/.config; then
