Update Image Partition Dumper.yml

diff --git a/.github/workflows/Image Partition Dumper.yml b/.github/workflows/Image Partition Dumper.yml
--- a/.github/workflows/Image Partition Dumper.yml
+++ b/.github/workflows/Image Partition Dumper.yml
@@ -353,8 +353,8 @@ jobs:
               echo "✔️ Vendor Mounted Successfully"
 
               # Debug
-              echo "📁 Vendor Mount Contents:"
-              ls -R vendor_mount | head -n 50
+              echo "📂 Checking extracted files:"
+              ls -lh output/ || echo "⚠️ Output / Folder Missing"
 
               echo "📦 Reading Vendor Build Properties"
 
