Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -2053,18 +2053,34 @@ jobs:
 
       - name: 🔧 Apply Fake Patches
         if: ${{ github.event.inputs.SUSFSREPOSITORY != '-1' }}
+        shell: bash
         run: |
-          set -e
+          set -Eeuo pipefail
 
-          SCRIPT="$GITHUB_WORKSPACE/FakePatches.kts"
-          WORKDIR="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/common"
+          # Paths
+          PDIR="${GITHUB_WORKSPACE}/kernel_workspace/AndreiMikh-Kernel-Lab/scripts"
+          WORKDIR="${GITHUB_WORKSPACE}/kernel_workspace/kernel_platform/common"
+          SCRIPT="${PDIR}/FakePatches.kts"
 
-          curl -L --fail --retry 3 \
-            "https://raw.githubusercontent.com/AndreiMikh/AndreiMikh-Kernel-Lab/LiquidAndrei/scripts/FakePatches.kts" \
-            -o "$SCRIPT"
-          
+          echo "📌 Script   : $SCRIPT"
+          echo "📌 Work Dir : $WORKDIR"
+
+          [[ -f "$SCRIPT" ]] || {
+            echo "⚠️ FakePatches Kotlin Script Not Found"
+            exit 1
+          }
+
+          [[ -d "$WORKDIR" ]] || {
+            echo "⚠️ Kernel Common Directory Not Found"
+            exit 1
+          }
+
+          echo "🔧 Applying Fake Patches..."
           kotlinc -script "$SCRIPT" apply "$WORKDIR"
-          
+
+          echo ""
+          echo "🎉 Fake Patches Applied Successfully"
+     
       - name: 🔧 SUSFS Patches (Auto Official / Fallback)and Kernel Compatibility Patches
         if: ${{ github.event.inputs.SUSFSREPOSITORY != '-1' }}
         env:
@@ -2419,19 +2435,35 @@ jobs:
 
       - name: 🔧 Revert Fake Patches
         if: ${{ github.event.inputs.SUSFSREPOSITORY != '-1' }}
+        shell: bash
         run: |
-          set -e
+          set -Eeuo pipefail
 
-          SCRIPT="$GITHUB_WORKSPACE/FakePatches.kts"
-          WORKDIR="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/common"
+          # Paths
+          PDIR="${GITHUB_WORKSPACE}/kernel_workspace/AndreiMikh-Kernel-Lab/scripts"
+          WORKDIR="${GITHUB_WORKSPACE}/kernel_workspace/kernel_platform/common"
+          SCRIPT="${PDIR}/FakePatches.kts"
 
-          curl -L --fail --retry 3 \
-            "https://raw.githubusercontent.com/AndreiMikh/AndreiMikh-Kernel-Lab/LiquidAndrei/scripts/FakePatches.kts" \
-            -o "$SCRIPT"
-          
+          echo "📌 Script   : $SCRIPT"
+          echo "📌 Work Dir : $WORKDIR"
+
+          [[ -f "$SCRIPT" ]] || {
+            echo "⚠️ FakePatches Kotlin Script Not Found"
+            exit 1
+          }
+
+          [[ -d "$WORKDIR" ]] || {
+            echo "⚠️ Kernel Common Directory Not Found"
+            exit 1
+          }
+
+          echo "🔧 Reversing Fake Patches..."
           kotlinc -script "$SCRIPT" postfix "$WORKDIR"
           kotlinc -script "$SCRIPT" revert "$WORKDIR"
      
+          echo ""
+          echo "🎉 Fake Patches Reverted"          
+
       - name: 🔧 LZ4 1.10.0 / ZSTD 1.5.7 Setup
         if: ${{ github.event.inputs.ZRAMCUSTOMPATCH != 'None' && github.event.inputs.ZRAMCUSTOMPATCH != '' }}
         shell: bash
