Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -2737,6 +2737,9 @@ jobs:
             if [[ "$PATCHNAME" == "001-lz4.patch" ]]; then
               git apply --ignore-whitespace -p1 < "$PATCHFILE" || echo "⚠️ $PATCHNAME Patch Failed, but Continuing..."
               echo "✔️ $PATCHNAME Patch Applied"
+            elif [[ "$PATCHNAME" == "002-zstd.patch" ]]; then
+              git apply --ignore-whitespace -p1 < "$PATCHFILE" || echo "⚠️ $PATCHNAME Patch Failed, but Continuing..."
+              echo "✔️ $PATCHNAME Patch Applied"
             else
               patch --ignore-whitespace -p1 < "$PATCHFILE" || echo "⚠️ $PATCHNAME Patch Failed, but Continuing..."
               echo "✔️ $PATCHNAME Patch Applied"
