Update Main V2.yml

diff --git a/.github/workflows/Main V2.yml b/.github/workflows/Main V2.yml
--- a/.github/workflows/Main V2.yml
+++ b/.github/workflows/Main V2.yml
@@ -289,6 +289,9 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           set -euo pipefail
+
+          command -v jq >/dev/null || { echo "❌ ERROR: JQ Not Installed"; exit 1; }
+          
           cd "$GITHUB_WORKSPACE"
           
           echo "--------------------------"
