Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -2048,6 +2048,8 @@ jobs:
           ANDROIDVERSION: ${{ env.ANDROIDVERSION }}
           KERNELVERSION: ${{ env.KERNELVERSION }}
           XUS: ${{ env.XUS }}
+          KV2: ${{ env.KV2 }}
+          KV3: ${{ env.KV3 }} 
         run: |
           set -euo pipefail
       
@@ -2074,21 +2076,21 @@ jobs:
           echo
 
           # Environment Information
-          echo "🧾 Android Version : $ANDROIDVERSION"
-          echo "🧾 Kernel Version  : $KERNELVERSION"
-          echo "🔎 Detected Kernel Base: $GKIVERSION"
+          echo "🧾 Android Version : ${ANDROIDVERSION}"
+          echo "🧾 Kernel Version  : ${KERNELVERSION}"
+          echo "🔎 Detected Kernel Base: ${GKIVERSION}"
           echo
          
-          echo "🔎 Detected Kernel Base: $GKIVERSION"
+          echo "🔎 Detected Kernel Base: ${GKIVERSION}"
       
           # Detect Kernel Common Directory
           if [[ -d "./kernel_platform/common" ]]; then
-              KDIR="./kernel_platform/common"
+            KDIR="./kernel_platform/common"
           elif [[ -d "./common" ]]; then
-              KDIR="./common"
+            KDIR="./common"
           else
-              echo "⚠️ ERROR: Kernel Common Directory Not Found!"
-              exit 1
+            echo "⚠️ ERROR: Kernel Common Directory Not Found!"
+            exit 1
           fi
       
           echo "📁 Kernel Directory: $KDIR"
@@ -2156,7 +2158,7 @@ jobs:
           if [[ "$SUSFSREPOSITORY" != "-1" ]]; then
 
             # Only Apply for 6.6.x Kernel Series
-            if [[ "$KERNELVERSION" == 6.6* ]]; then
+            if [[ "${KV2}" == "66" && "${KV3}" -le 6630 && "$SUSFSREPOSITORY" != "-1" ]]; then          
               echo "🔧 Checking TrustyOS Requirement for Kernel 6.6.x..."
 
               TRUSTYEXISTS=false
@@ -2201,9 +2203,9 @@ jobs:
           if [[ "$SUSFSREPOSITORY" != "-1" ]]; then          
             FAKEPATCHED=0          
             # Android 15 Kernel 6.6 Fix
-            if [[ "$GKIVERSION" == "android15-6.6" ]]; then          
+            if [[ "${GKIVERSION}" == "android15-6.6" ]]; then          
               if ! grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' ./fs/proc/task_mmu.c; then
-                echo "⚠️ Missing NR Subpages Fix 🛠️ Applying Temporary Patch"          
+                echo "⚠️ Missing NR Subpages Fix 🔧 Applying Temporary Patch"          
                 sed -i \
                   -e '/int ret = 0, copied = 0;/a \\tunsigned int nr_subpages \= __PAGE_SIZE \/ PAGE_SIZE;' \
                   -e '/int ret = 0, copied = 0;/a \\tpagemap_entry_t \*res = NULL;' \
@@ -2212,28 +2214,28 @@ jobs:
               fi
           
               if ! grep -qxF '#include <linux/dma-buf.h>' ./fs/proc/base.c; then
-                echo "📩 Adding Missing DMA-BUF Header"          
+                echo "🔧 Adding Missing DMA-BUF Header"          
                 sed -i '/#include <linux\/cpufreq_times.h>/a #include <linux\/dma-buf.h>' ./fs/proc/base.c
               fi
             fi
                     
             # Android 14 Kernel 6.1 Fix
-            if [[ "$GKIVERSION" == "android14-6.1" ]]; then          
+            if [[ "${GKIVERSION}" == "android14-6.1" ]]; then          
               if ! grep -qxF $'\tif (!vma_pages(vma))' ./fs/proc/task_mmu.c; then
-                echo "🛠️ Missing VMA Pages Fix"
+                echo "🔧 Missing VMA Pages Fix"
                 FAKEPATCHED=1
               fi
           
               if ! grep -qxF '#include <linux/dma-buf.h>' ./fs/proc/base.c; then
-                echo "📩 Adding DMA-BUF Header"          
+                echo "🔧 Adding DMA-BUF Header"          
                 sed -i '/#include <linux\/cpufreq_times.h>/a #include <linux\/dma-buf.h>' ./fs/proc/base.c
               fi
             fi          
           
             # Android 12 / 13 Fix
-            if [[ "$GKIVERSION" == "android12-5.10" || "$GKIVERSION" == "android13-5.15" ]]; then          
+            if [[ "${GKIVERSION}" == "android12-5.10" || "$GKIVERSION" == "android13-5.15" ]]; then          
               if ! grep -qxF $'\tif (!vma_pages(vma))' ./fs/proc/task_mmu.c; then
-                echo "🛠️ Missing VMA Pages Fix"
+                echo "🔧 Missing VMA Pages Fix"
                 FAKEPATCHED=1
               fi
             fi  
@@ -2247,7 +2249,7 @@ jobs:
             PATCH69FILE="hide.patch"
 
             SUPPORTEDOGKI() {
-              case "$GKIVERSION" in
+              case "${GKIVERSION}" in
                 android14-6.1|android15-6.1|android15-6.6) return 0 ;;
                 *) return 1 ;;
               esac
