Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -300,12 +300,8 @@ jobs:
       # ==============================
       # Compiler Cache
       # ==============================
-      # Directories
-      CCACHE_DIR: ${{ github.workspace }}/.ccache
-      CCACHE_BASEDIR: ${{ github.workspace }}/kernel_workspace
-
       # Kernel Builds
-      CCACHE_COMPILERCHECK: content
+      CCACHE_COMPILERCHECK: "none"
       CCACHE_NOHASHDIR: "true"
       CCACHE_NOHARDLINK: "true"
 
@@ -892,7 +888,18 @@ jobs:
       
           echo ""
           echo "🎉 Git Configuration Applied:"
-          git config --global --list      
+          git config --global --list   
+
+      # ==============================
+      # Cache Environment Directory
+      # ==============================
+      - name: Cache Environment Directory
+        if: ${{ env.BUILDCCACHE != 'Disabled' }}
+        run: |
+          echo "CCACHE_DIR=$HOME/.ccache_${{ github.event.inputs.FILE }}" >> $GITHUB_ENV
+          mkdir -p "$HOME/.ccache_${{ github.event.inputs.FILE }}"
+          echo ""
+          echo "🚀 Set: $HOME/.ccache_${{ github.event.inputs.FILE }}"
 
       # ==============================
       # Local Cache Restoration
@@ -907,8 +914,6 @@ jobs:
           restore-keys: |
             CCache-${{ runner.os }}-${{ env.MANIFESTBASEFILE }}-${{ env.CPUD }}-
             CCache-${{ runner.os }}-${{ env.MANIFESTBASEFILE }}-
-            CCache-${{ runner.os }}-
-            CCache-
             
       # ==============================
       # Release Cache Restoration
@@ -4543,7 +4548,7 @@ jobs:
           export CCACHE_LOGFILE="${{ github.workspace }}/kernel_workspace/ccache.log" || echo "⚠️ Cache Log Not Found"
           export CCACHE_DIR="${{ env.CCACHE_DIR }}" || echo "⚠️ Directory Not Available"
           export CCACHE_COMPILERCHECK="${{ env.CCACHE_COMPILERCHECK }}" || echo "⚠️ Compiler Check Not Found"
-          export CCACHE_BASEDIR="${{ env.CCACHE_BASEDIR }}" || echo "⚠️ Base Directory Not Found"
+          export CCACHE_BASEDIR="$GITHUB_WORKSPACE" || echo "⚠️ Base Directory Not Found"
           export CCACHE_NOHASHDIR="${{ env.CCACHE_NOHASHDIR }}" || echo "⚠️ NoHash Directory Not Found"
           export CCACHE_NOHARDLINK="${{ env.CCACHE_NOHARDLINK }}" || echo "⚠️ Cache Hardlink Not Found"    
                    
