Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -2580,6 +2580,7 @@ jobs:
                 ./fs/proc/task_mmu.c; then
                 echo "⚠️ Missing NR Subpages Definition Detected"
                 echo "🔧 Applying Temporary Task MMU Compatibility Patch"        
+         
                 sed -i \
                   -e '/int ret = 0, copied = 0;/a \\tunsigned int nr_subpages \= __PAGE_SIZE \/ PAGE_SIZE;' \
                   -e '/int ret = 0, copied = 0;/a \\tpagemap_entry_t \*res = NULL;' \
@@ -2592,43 +2593,52 @@ jobs:
                 ./fs/proc/base.c; then
                 echo "⚠️ Missing DMA-BUF Header Detected"
                 echo "🔧 Injecting Required Header"   
+         
                 sed -i '/#include <linux\/cpufreq_times.h>/a #include <linux\/dma-buf.h>' ./fs/proc/base.c
               fi
 
               # Add Missing ZSwap Header
-              if ! grep -qxF '#include <linux/zswap.h>' \
-                ./mm/memory.c; then        
-                echo "⚠️ Missing ZSwap Header Detected"
-                echo "🔧 Injecting Required Header"        
-                sed -i \
-                  '/#include <linux\/sched\/sysctl\.h>/a #include <linux\/zswap.h>' \
-                  ./mm/memory.c        
-                fake_patched_swap=1
+              if [[ "${{ github.event.inputs.SUSFSVARIANT }}" == "GKI" ]]; then
+              
+                if ! grep -qxF '#include <linux/zswap.h>' \
+                  ./mm/memory.c; then              
+                  echo "⚠️ Missing ZSwap Header Detected"
+                  echo "🔧 Injecting Required Header"
+              
+                  sed -i \
+                    '/#include <linux\/sched\/sysctl\.h>/a #include <linux\/zswap.h>' \
+                    ./mm/memory.c
+              
+                  fake_patched_swap=1
+                fi
+              
+                # Add Missing Trace / Hooks / FS Header
+                if ! grep -qxF '#include <trace/hooks/fs.h>' ./fs/namespace.c \
+                  && ! grep -qxF 'susfs_def.h' ./fs/namespace.c; then              
+                  echo "⚠️ Missing Trace / Hooks / FS Header Detected"
+                  echo "🔧 Injecting Required Header"
+              
+                  sed -i \
+                    '/#include <trace\/hooks\/blk\.h>/a #include <trace\/hooks\/fs.h>' \
+                    ./fs/namespace.c
+              
+                  fake_patched_ns=1
+                fi
+              
+                # Expand Single-Line if Block
+                # Required for SUSFS Pattern Matching
+                if grep -qF 'if (vma->vm_end > last_vma_end)' ./fs/proc/task_mmu.c \
+                  && ! grep -qF 'if (vma->vm_end > last_vma_end) {' ./fs/proc/task_mmu.c; then              
+                  echo "⚠️ Compact if Block Detected"
+                  echo "🔧 Expanding Block for SUSFS Compatibility"
+              
+                  perl -i -0pe \
+                    's/\t\t\tif \(vma->vm_end > last_vma_end\)\n\t\t\t\tsmap_gather_stats\(vma, &mss, last_vma_end\);/\t\t\tif (vma->vm_end > last_vma_end) {\n\t\t\t\tsmap_gather_stats(vma, \&mss, last_vma_end);\n\t\t\t\tlast_vma_end = vma->vm_end;\n\t\t\t}/' \
+                    ./fs/proc/task_mmu.c
+              
+                  fake_patched_expand=1
+                fi              
               fi
-  
-              # Add Missing Trace / Hooks / FS Header
-              if ! grep -qxF '#include <trace/hooks/fs.h>' ./fs/namespace.c \
-                && ! grep -qxF 'susfs_def.h' ./fs/namespace.c; then        
-                echo "⚠️ Missing Trace / Hooks / FS Header Detected"
-                echo "🔧 Injecting Required Header"      
-                sed -i \
-                  '/#include <trace\/hooks\/blk\.h>/a #include <trace\/hooks\/fs.h>' \
-                  ./fs/namespace.c        
-                fake_patched_ns=1
-              fi
-  
-              # Expand Single-Line if Block
-              # Required for SUSFS Pattern Matching
-              if grep -qF 'if (vma->vm_end > last_vma_end)' ./fs/proc/task_mmu.c \
-                && ! grep -qF 'if (vma->vm_end > last_vma_end) {' ./fs/proc/task_mmu.c; then        
-                echo "⚠️ Compact if Block Detected"
-                echo "🔧 Expanding Block for SUSFS Compatibility"       
-                perl -i -0pe \
-                  's/\t\t\tif \(vma->vm_end > last_vma_end\)\n\t\t\t\tsmap_gather_stats\(vma, &mss, last_vma_end\);/\t\t\tif (vma->vm_end > last_vma_end) {\n\t\t\t\tsmap_gather_stats(vma, \&mss, last_vma_end);\n\t\t\t\tlast_vma_end = vma->vm_end;\n\t\t\t}/' \
-                  ./fs/proc/task_mmu.c        
-                fake_patched_expand=1
-              fi
-            fi
                     
             # Android 14 Kernel 6.1 Fix
             if [ "$KMI" = "android14-6.1" ]; then
@@ -2643,6 +2653,7 @@ jobs:
               if ! grep -qxF '#include <linux/dma-buf.h>' ./fs/proc/base.c; then
                 echo "⚠️ Missing DMA-BUF Header Detected"
                 echo "🔧 Injecting Required Header"        
+         
                 sed -i \
                   '/#include <linux\/cpufreq_times.h>/a #include <linux\/dma-buf.h>' \
                   ./fs/proc/base.c
@@ -2668,6 +2679,7 @@ jobs:
                 && ! grep -qxF '#include <linux/susfs_def.h>' ./mm/memory.c; then         
                 echo "⚠️ Conflicting Swap Slots Include Detected"
                 echo "🔧 Removing Conflicting Include Temporarily"          
+         
                 sed -i '/#include <linux\/swap_slots\.h>/d' \
                   ./mm/memory.c          
                 fake_patched_dist=1
