Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -2042,6 +2042,7 @@ jobs:
           SUSFSBRANCHDEV: ${{ github.event.inputs.SUSFSBRANCHDEV }}
           FILE: ${{ github.event.inputs.FILE }}
           NTSYNC: ${{ github.event.inputs.NTSYNC }}
+          ZRAM: ${{ github.event.inputs.ZRAMALGORITHM }}
           ANDROIDVERSION: ${{ env.ANDROIDVERSION }}
           KERNELVERSION: ${{ env.KERNELVERSION }}
           XUS: ${{ env.XUS }}
@@ -2063,9 +2064,11 @@ jobs:
           cd kernel_workspace
 
           # Clone Required Patch Repositories
-          echo "📥 Cloning Dependencies..."
-          git clone --depth=1 https://github.com/AndreiMikh/AndreiMikh-Kernel-Lab.git || true
-
+          echo "📥 Cloning Github Owner Patches and SukiSU Patches Dependencies for Later Steps..."
+      
+          git clone --depth=1 https://github.com/SukiSU-Ultra/SukiSU_patch.git
+          git clone --depth=1 https://github.com/AndreiMikh/AndreiMikh-Kernel-Lab.git
+         
           echo "✔️ Patch Repositories Cloned"
           echo
 
@@ -2140,13 +2143,32 @@ jobs:
           fi
       
           SUSFSPATCH="${SUSFSPATCHLIST[-1]}"
+          
+          ZRAMSRC="${GITHUB_WORKSPACE}/kernel_workspace/SukiSU_patch/other/zram"
       
-          echo "🧾 Using Patch: $SUSFSPATCH"
-      
-          cp "$SUSFSPATCH" "$KDIR/"
-          cp -r ./susfs4ksu/kernel_patches/fs/* "$KDIR/fs/" || true
-          cp -r ./susfs4ksu/kernel_patches/include/linux/* "$KDIR/include/linux/" || true
+          echo "🧾 Using Patch for SUSFS: $SUSFSPATCH"
+          echo "🧾 Using Patch for ZRAM: $SRC"
 
+          if [[ "$SUSFSREPOSITORY" != "-1" ]]; then
+            echo "📥 Copying SUSFS Patches..."  
+            cp "$SUSFSPATCH" "$KDIR/"
+            cp -r ./susfs4ksu/kernel_patches/fs/* "$KDIR/fs/" || true
+            cp -r ./susfs4ksu/kernel_patches/include/linux/* "$KDIR/include/linux/" || true
+          fi
+
+          if [[ "$ZRAM" == 1* ]]; then
+            echo "📥 Copying SukiSU Patches for Later Steps..."
+            cp -r "$ZRAMSRC/lz4k/include/linux/." "$KDIR/include/linux/" 2>/dev/null || \
+              echo "⚠️ Failed to Copy Include/Linux"          
+            cp -r "$ZRAMSRC/lz4k/lib/." "$KDIR/lib/" 2>/dev/null || \
+              echo "⚠️ Failed to Copy Lib"        
+            cp -r "$ZRAMSRC/lz4k/crypto/." "$KDIR/crypto/" 2>/dev/null || \
+              echo "⚠️ Failed to Copy Crypto"          
+            cp -r "$ZRAMSRC/lz4k_oplus/." "$KDIR/lib/lz4k_oplus/" 2>/dev/null || \
+              echo "⚠️ Failed to Copy LZ4K OPlus"
+          fi
+
+          # Navigate to Directory
           cd "$KDIR"
 
           # TrustyOS Missing Fix (6.6)     
