Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -2456,6 +2456,30 @@ jobs:
                 fi
               fi
 
+              # Add Missing SUSFS Header
+              if (( SUBLEVEL == 89 )); then
+                if [[ -f ./include/linux/susfs_def.h ]]; then
+                  if ! grep -qF '#include <linux/susfs_def.h>' ./fs/proc/base.c; then
+                    if grep -qF '#include <linux/dma-buf.h>' ./fs/proc/base.c; then
+                      echo "⚠️ Missing SUSFS Header Detected"
+                      echo "🔧 Injecting Required SUSFS Header..."
+                      perl -0pi -e \
+                        's|(#include <linux/dma-buf\.h>\n)|$1#if defined(CONFIG_KSU_SUSFS_SUS_MAP) || defined(CONFIG_KSU_SUSFS_OPEN_REDIRECT)\n#include <linux/susfs_def.h>\n#endif\n|' \
+                        ./fs/proc/base.c
+                      echo "☘️ SUSFS Header Successfully Injected"
+                    else
+                      echo "⚠️ Injection Point (Linux / DMA-BUF Headers) Not Found"
+                      echo "⏭️ Skipping SUSFS Header Injection"
+                    fi
+                  else
+                    echo "☘️ SUSFS Header Already Present"
+                  fi
+                else
+                  echo "⚠️ SUSFS Header Not Found"
+                  echo "⏭️ Skipping SUSFS Header Injection"
+                fi
+              fi
+
               # Add Missing DMA-BUF Header
               if (( SUBLEVEL <= 92 )); then
                 if ! grep -qxF '#include <linux/dma-buf.h>' \
