Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -2006,11 +2006,33 @@ jobs:
           echo "------------------------------"
           echo ""
 
+      - name: 🔢 Extract Kernel Sublevel
+        run: |
+          cd "$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/common"
+
+          # Extract Sublevel
+          SUBLEVEL=$(grep '^SUBLEVEL *=' Makefile | head -n1 | cut -d= -f2 | tr -d ' ')
+
+          # Fallback if Empty
+          SUBLEVEL="${SUBLEVEL:-0}"
+
+          # Validate Numeric
+          if ! [[ "$SUBLEVEL" =~ ^[0-9]+$ ]]; then
+            echo "⚠️ Invalid Sublevel Detected: $SUBLEVEL — Forcing 0"
+            SUBLEVEL=0
+          fi
+
+          echo "SUBLEVEL=$SUBLEVEL" >> "$GITHUB_ENV"
+          echo "📌 Kernel Sublevel: $SUBLEVEL"
+
       - name: 🔧 Apply Fake Patches
         if: ${{ github.event.inputs.SUSFSREPOSITORY != '-1' }}
         run: |
-          kotlinc -script "$GITHUB_WORKSPACE/kernel_workspace/AndreiMikh-Kernel-Lab/scripts/PatchFakePatches.kts" apply "$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/common"          
-          
+          SCRIPT="$GITHUB_WORKSPACE/scripts/FakePatches.kts"
+          WORKDIR="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/common"
+
+          kotlinc -script "$SCRIPT" apply "$WORKDIR"
+      
       - name: 🔧 SUSFS Patches (Auto Official / Fallback)and Kernel Compatibility Patches
         if: ${{ github.event.inputs.SUSFSREPOSITORY != '-1' }}
         env:
@@ -2113,20 +2135,6 @@ jobs:
           
           echo "📁 Kernel Directory: $KDIR"
           echo
-
-          # Extract Sublevel
-          SUBLEVEL=$(grep '^SUBLEVEL *=' Makefile | head -n1 | cut -d= -f2 | tr -d ' ')          
-          # Fallback if Empty
-          SUBLEVEL="${SUBLEVEL:-0}"          
-          # Validate Numeric
-          if ! [[ "$SUBLEVEL" =~ ^[0-9]+$ ]]; then
-            echo "⚠️ Invalid Sublevel Detected: $SUBLEVEL — Forcing 0"
-            SUBLEVEL=0
-          fi
-          
-          echo "📂 Kernel Base   : $GKIVERSION"
-          echo "📂 Sublevel      : $SUBLEVEL"
-          echo ""
       
           # Clone SUSFS Meta Repository
           echo "📥 Cloning SUSFS..."      
@@ -2384,9 +2392,12 @@ jobs:
       - name: 🔧 Revert Fake Patches
         if: ${{ github.event.inputs.SUSFSREPOSITORY != '-1' }}
         run: |
-          kotlinc -script "$GITHUB_WORKSPACE/kernel_workspace/AndreiMikh-Kernel-Lab/scripts/PatchFakePatches.kts" postfix "$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/common"
-          kotlinc -script "$GITHUB_WORKSPACE/kernel_workspace/AndreiMikh-Kernel-Lab/scripts/PatchFakePatches.kts" revert "$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/common"  
+          SCRIPT="$GITHUB_WORKSPACE/scripts/FakePatches.kts"
+          WORKDIR="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/common"
 
+          kotlinc -script "$SCRIPT" postfix "$WORKDIR"
+          kotlinc -script "$SCRIPT" revert "$WORKDIR"
+     
       - name: 🔧 LZ4 1.10.0 / ZSTD 1.5.7 Setup
         if: ${{ github.event.inputs.ZRAMCUSTOMPATCH != 'None' && github.event.inputs.ZRAMCUSTOMPATCH != '' }}
         shell: bash
