Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -1922,6 +1922,25 @@ jobs:
             KSU_GIT_TAG=$(gitlatesttag "$KSUREPO")
             sed -i "s/KSU_VERSION_TAG_FALLBACK := v0.0.1/KSU_VERSION_TAG_FALLBACK := $KSU_GIT_TAG/" kernel/Kbuild
 
+            # Apply KSU-Next Static SELinux Fix
+            PDIR="${GITHUB_WORKSPACE}/kernel_workspace/AndreiMikh-Kernel-Lab/patches"
+            STATICFILE="${PDIR}/KSU-Next-Static.patch"
+            
+            if [[ ! -f "${STATICFILE}" ]]; then
+              echo "⚠️ Kernel-Next Static SELinux patch not found:"
+              echo "   ${STATICFILE}"
+              exit 1
+            fi
+            
+            echo "🔧 Applying KSU-Next Static SELinux Fix..."
+            
+            if patch -p1 < "${STATICFILE}"; then
+              echo "✔️ Kernel-Next Static SELinux Fix Applied"
+            else
+              echo "⚠️ Failed to Apply Kernel-Next Static SELinux Fix"
+              exit 1
+            fi
+
             # Report SUSFS Inline Hook Mode
             if [[ "$SUSFS" != "-1" && -f kernel/supercall/dispatch.c ]]; then
               echo "🔧 Setting Hook Mode to Inline..."
