Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -2282,14 +2282,23 @@ jobs:
                 ;;
             esac
 
+            # Verify the Patch URL Exists
+            echo "🔍 Checking Patch URL..."
+            if ! wget --spider "$SUSFS10URL"; then
+              echo "⚠️ ERROR: Patch does Not Exist:"
+              echo "$SUSFS10URL"
+              exit 1
+            fi
+
             echo "🌐 Downloading Patch: $SUSFS10URL"
-            if ! wget -q "$SUSFS10URL" -O enable.patch; then
+            if ! wget "$SUSFS10URL" -O enable.patch; then
               echo "⚠️ ERROR: Failed to Download SUSFS Enable Patch"
               exit 1
             fi
             APPLIED=false
             for pathprefix in 0 1 2; do
-              if patch -p$pathprefix < enable.patch; then
+              echo "Trying -p$pathprefix..."
+              if patch --forward -p"$pathprefix" < enable.patch; then
                 APPLIED=true
                 break
               fi
