Update Main V2.yml

diff --git a/.github/workflows/Main V2.yml b/.github/workflows/Main V2.yml
--- a/.github/workflows/Main V2.yml
+++ b/.github/workflows/Main V2.yml
@@ -1589,15 +1589,15 @@ jobs:
       
           cd "$KDIR"
       
-          # ------------------------------
-          # Apply SUSFS Meta Patch
-          # ------------------------------
+          # -----------------------------
+          # Apply SUSFS Meta Core Patch
+          # -----------------------------
           echo "🚀 Applying SUSFS Meta Core Patch..."
-      
-          patch -p1 < "$(basename "$SUS_PATCH")" || true
-      
-          echo "✔️ SUSFS Meta Patch Applied"
-          echo
+          if ! patch -p1 < "$SUS_PATCH"; then
+              echo "⚠️ SUSFS Core Patch Failed: $SUS_PATCH"
+              exit 1
+          fi
+          echo "✔️ SUSFS Meta Core Patch Applied"
       
           # ------------------------------
           # Apply Hide Patch
@@ -1624,7 +1624,7 @@ jobs:
           echo
       
           # ------------------------------
-          # Apply KernelSU Enable Patch
+          # Apply KernelSU SUSFS Enable Patch (Optional)
           # ------------------------------
           KSU_META="${{ github.event.inputs.KSU_META }}"
       
