Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -3945,6 +3945,7 @@ jobs:
           echo ""
 
           # Paths
+          KMI="${{ env.KMI }}"
           PDIR="${GITHUB_WORKSPACE}/kernel_workspace/AndreiMikh-Kernel-Lab/patches"
           TARGETPATH="kernel_workspace/kernel_platform/common"
 
@@ -3954,6 +3955,29 @@ jobs:
           fi
 
           cd "$TARGETPATH"
+
+          # Android 16 / Kernel 6.12 Compatibility Fixes
+          if [ "${KMI:-}" = "android16-6.12" ]; then
+            echo "🔧 Applying Android16-6.12 Compatibility Fixes..."
+
+            # Remove NTSync Headers and Driver Sources
+            # To Avoid Unsupported Build Vonflicts
+            rm -f include/uapi/linux/ntsync.h
+            rm -f drivers/misc/ntsync.c
+            echo "🔧 Adding Missing IPC Namespace Symbol Exports..."
+
+            # Export Put IPC NS Symbol if Not Already Exported
+            # Required by External Modules and Root Implementations
+            if ! grep -q 'EXPORT_SYMBOL.*put_ipc_ns' ./ipc/namespace.c; then
+              echo -e '\nEXPORT_SYMBOL_GPL(put_ipc_ns);' >> ./ipc/namespace.c
+            fi
+
+            # Export Init IPC NS Symbol if Not Already Exported
+            # Needed for IPC Namespace Access from External Modules
+            if ! grep -q 'EXPORT_SYMBOL.*init_ipc_ns' ./ipc/msgutil.c; then
+              echo -e '\nEXPORT_SYMBOL_GPL(init_ipc_ns);' >> ./ipc/msgutil.c
+            fi
+          fi
 
           # Function: Patch Apply
           apply() {
