Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -1120,12 +1120,12 @@ jobs:
       
           # Core Runtime Configuration
           export CCACHE_DIR="${{ env.CCACHE_DIR }}" || echo "⚠️ Directory Not Available"
-          export CCACHE_COMPILERCHECK="${{ env.CCACHE_COMPILERCHECK }}" || echo "⚠️ Compiler Check Not Found"
-          export CCACHE_SLOPPINESS="${{ env.CCACHE_SLOPPINESS }}" || echo "⚠️ Sloppiness Not Found"
-          export CCACHE_BASEDIR="${{ env.CCACHE_BASEDIR }}" || echo "⚠️ Base Directory Not Found"
-          export CCACHE_NOHASHDIR="${{ env.CCACHE_NOHASHDIR }}" || echo "⚠️ NoHash Directory Not Found"
-          export CCACHE_NOHARDLINK="${{ env.CCACHE_NOHARDLINK }}" || echo "⚠️ Cache Hardlink Not Found"                 
-      
+          export CCACHE_COMPILERCHECK="${{ env.CCACHE_COMPILERCHECK }}" || echo "⚠️ Not Found"          
+          export CCACHE_BASEDIR="${{ env.CCACHE_BASEDIR }}" || echo "⚠️ Not Found"
+          export CCACHE_NOHASHDIR="${{ env.CCACHE_NOHASHDIR }}" || echo "⚠️ Not Found"
+          export CCACHE_NOHARDLINK="${{ env.CCACHE_NOHARDLINK }}" || echo "⚠️ Not Found"                 
+          export CCACHE_IS_KERNEL_COMPILING="${{ env.CCACHE_IS_KERNEL_COMPILING }}" || echo "⚠️ Not Found"                 
+       
           # Cache Size
           ccache -M "${CCACHE_MAXSIZE}"
       
