Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -3104,15 +3104,22 @@ jobs:
           set -euo pipefail
 
           # Kernel Source and Patch Directory
-          KDIR="${GITHUB_WORKSPACE}/kernel_workspace/common"
+          KDIR="${GITHUB_WORKSPACE}/kernel_workspace/kernel_platform/common"
           PDIR="${GITHUB_WORKSPACE}/kernel_workspace/AndreiMikh-Kernel-Lab/patches"
           PATCHFILE="RTMutex-6.6.patch"
-          PATCH="${PDIR}/${PATCHFILE}"
-          
+          PATCH="${PDIR}/RTMutex-6.6.patch"
+
+          # Verify Paths
+          [[ -d "$KDIR" ]] || {
+            echo "⚠️ Kernel Source Directory Not Found:"
+            echo "$KDIR"
+            exit 1
+          }
+                    
           [[ -f "$PATCH" ]] || {
-              echo "⚠️ Patch Not Found:"
-              echo "$PATCH"
-              exit 1
+            echo "⚠️ Patch Not Found:"
+            echo "$PATCH"
+            exit 1
           }
 
           # Check for Patch Reject Files
