Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -2339,8 +2339,7 @@ jobs:
           echo "🔎 Detected Kernel Base: $GKIVERSION"
           echo
          
-          echo "🔎 Detected Kernel Base: $GKIVERSION"
-      
+          echo "🔎 Detected Kernel Base: $GKIVERSION"      
           # Detect Kernel Common Directory
           if [[ -d "./kernel_platform/common" ]]; then
             KDIR="./kernel_platform/common"
@@ -2349,75 +2348,88 @@ jobs:
           else
             echo "⚠️ ERROR: Kernel Common Directory Not Found!"
             exit 1
-          fi
-      
+          fi      
           echo "📁 Kernel Directory: $KDIR"
           echo
       
           # Clone SUSFS Meta Repository
-          echo "📥 Cloning SUSFS..."
-      
-          BRANCH="gki-${ANDROIDVERSION}-${KERNELVERSION}"
-      
+          echo "📥 Cloning SUSFS..."      
+          BRANCH="gki-${ANDROIDVERSION}-${KERNELVERSION}"      
           if [[ "$SUSFSVARIANT" == "OGKI" ]]; then
-            BRANCH="oki-${ANDROIDVERSION}-${KERNELVERSION}"
-         
+            BRANCH="oki-${ANDROIDVERSION}-${KERNELVERSION}"        
             if [[ "$SUSFSBRANCHDEV" == "true" ]]; then
               BRANCH="${BRANCH}-dev"
             fi
-            git clone --depth=1 https://github.com/cctv18/susfs4oki.git susfs4ksu -b "$BRANCH"
-      
+            git clone --depth=1 https://github.com/cctv18/susfs4oki.git susfs4ksu -b "$BRANCH"      
           else           
             if [[ "$SUSFSBRANCHDEV" == "true" ]]; then
               BRANCH="${BRANCH}-dev"
             fi
             git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu.git susfs4ksu -b "$BRANCH"
-          fi
-      
+          fi      
           echo "✔️ SUSFS Branch: $BRANCH"
       
-          # Optional SUSFS Meta Commit Checkout
+          # Optional SUSFS Revision Checkout
+          # - Full commit hashes
+          # - Short Commit Hashes          
           cd susfs4ksu || exit 1
+          
+          # Skip if SUSFS Revision is Empty or Disabled (-1)
+          if [[ -n "${SUSFSREPOSITORY:-}" && "${SUSFSREPOSITORY}" != "-1" ]]; then          
+            echo "🔎 SUSFS Revision: $SUSFSREPOSITORY"          
+            # Numeric Rollback Mode
+            if [[ "$SUSFSREPOSITORY" =~ ^[0-9]+$ ]]; then          
+              echo "📦 Fetching Additional Git History..."         
+              # Deepen Shallow Clone History
+              git fetch --deepen=$((SUSFSREPOSITORY + 20)) origin "$BRANCH"
+          
+              # Checkout Older SUSFS Revision
+              git checkout "HEAD~$SUSFSREPOSITORY" || {
+                echo "⚠️ Failed Checkout HEAD~$SUSFSREPOSITORY"
+                exit 1
+              }          
       
-          if [[ -n "$SUSFSREPOSITORY" ]]; then
-            echo "🔎 SUSFS Revision: $SUSFSREPOSITORY"
-      
-            if [[ "$SUSFSREPOSITORY" =~ ^[0-9]+$ ]]; then
-              git checkout "HEAD~$SUSFSREPOSITORY" || true
-            else
-              git checkout "$SUSFSREPOSITORY" || true
+            else          
+              # SUSFS Commit Hash / Tag / Branch Mode        
+              # Detect git commit hash format
+              if [[ "$SUSFSREPOSITORY" =~ ^[0-9a-fA-F]{7,40}$ ]]; then          
+                echo "📦 Fetching SUSFS Commit Object..."         
+                # Fetch Specific Commit for Shallow Clones
+                git fetch origin "$SUSFSREPOSITORY" --depth=1 || true
+              fi          
+        
+              # Checkout Requested Revision
+              git checkout "$SUSFSREPOSITORY" || {
+                echo "⚠️ Invalid SUSFS Revision"
+                exit 1
+              }
             fi
           fi
-      
+          
+          # Print Active Checked Out SUSFS Revision
+          echo "✔️ Active SUSFS Commit: $(git rev-parse --short HEAD)"          
           cd ..
       
           # Find SUSFS Patches
-          echo "🔎 Searching SUSFS Patches..."
-      
+          echo "🔎 Searching SUSFS Patches..."      
           shopt -s nullglob
-          SUSFSPATCHLIST=(./susfs4ksu/kernel_patches/50_add_susfs_in_gki-${ANDROIDVERSION}-${KERNELVERSION}*.patch)
-      
+          SUSFSPATCHLIST=(./susfs4ksu/kernel_patches/50_add_susfs_in_gki-${ANDROIDVERSION}-${KERNELVERSION}*.patch)      
           if [[ ${#SUSFSPATCHLIST[@]} -eq 0 ]]; then
             echo "⚠️ No SUSFS Patch Found"
             ls ./susfs4ksu/kernel_patches/ || true
             exit 1
-          fi
-      
+          fi      
           SUSFSPATCH="${SUSFSPATCHLIST[-1]}"
 
           # SukiSU ZRAM Patches
           ZRAMSRC="${GITHUB_WORKSPACE}/kernel_workspace/SukiSU_patch/other/zram"
-
           # CCTV18 LZ4 1.10.0 and ZSTD 1.5.7 Patches
           CUSTOMPATCH="${GITHUB_WORKSPACE}/kernel_workspace/oppo_oplus_realme_sm8750/zram_patch"
-
           # Xiao LZ4 1.10.0 and ZSTD 1.5.7 Patches
-          XMPATCH="${GITHUB_WORKSPACE}/kernel_workspace/kernel_patches/zram_patches"
-      
+          XMPATCH="${GITHUB_WORKSPACE}/kernel_workspace/kernel_patches/zram_patches"      
           echo "🧾 SUSFS Patch Directory: $SUSFSPATCH"
           echo "🧾 ZRAM Patch Directory: $ZRAMSRC"
           echo ""
-
           if [[ "$SUSFSREPOSITORY" != "-1" ]]; then
             echo "📥 Copying SUSFS Patches..."  
             cp "$SUSFSPATCH" "$KDIR/" 2>/dev/null || \
@@ -2466,37 +2478,31 @@ jobs:
           # SUSFS Core Patch (50 Add SUSFS Patch)
           echo "⚙️ Applying SUSFS Core Patch (50 Add SUSFS Patch)"
           patch -p1 --forward --fuzz=3 \
-            < "$(basename "$SUSFSPATCH")" || true
-          
+            < "$(basename "$SUSFSPATCH")" || true          
           # SUSFS 69 Enable Hide Patch
           PATCH69URL="https://raw.githubusercontent.com/AndreiMikh/AndreiMikh-Kernel-Lab/refs/heads/${GITHUB_REF_NAME}/patches/69_hide_stuff.patch"
           PATCH69FILE="hide.patch"
-
           SUPPORTEDOGKI() {
             case "$GKIVERSION" in
               android14-6.1|android15-6.1|android15-6.6) return 0 ;;
               *) return 1 ;;
             esac
           }
-
           SUPPORTEDENGINE() {
             [[ "$SUSFSVARIANT" == "OGKI" ]] || \
             [[ "$ROOTENGINE" == "ReSukiSU" ]]
           }
-
           if SUPPORTEDOGKI && SUPPORTEDENGINE; then
             echo "⚙️ Applying SUSFS 69 Enable Hide Patch to $ROOTENGINE..."
             if ! wget -q "$PATCH69URL" -O "$PATCH69FILE"; then
               echo "⚠️ Failed to Download SUSFS 69 Enable Hide Patch"
               exit 1
             fi
-
             if patch -p1 -N -F 3 < "$PATCH69FILE"; then
               echo "🔧 SUSFS 69 Enable Hide Patch Applied"
             else
               echo "⚠️ SUSFS 69 Enabled Hide Patch Not Applied (Already Applied or Failed)"
             fi
-
             rm -f "$PATCH69FILE"              
           else
             echo "⚠️ SUSFS 69 Enable Hide Patch Skipped (Unsupported Base)"
@@ -2510,7 +2516,6 @@ jobs:
             else
               PATCHBRANCH="gki-${ANDROIDVERSION}-${KERNELVERSION}"
             fi
-
             [[ "${SUSFSBRANCHDEV}" == "true" ]] && PATCHBRANCH="${PATCHBRANCH}-dev"
             case "$SUSFSVARIANT" in
               GKI)
@@ -2526,12 +2531,10 @@ jobs:
             esac
 
             echo "🌐 Downloading Patch: $SUSFS10URL"
-
             if ! wget -q "$SUSFS10URL" -O enable.patch; then
               echo "⚠️ ERROR: Failed to Download SUSFS Enable Patch"
               exit 1
             fi
-
             APPLIED=false
             for pathprefix in 0 1 2; do
               if patch -p$pathprefix < enable.patch; then
@@ -2539,9 +2542,7 @@ jobs:
                 break
               fi
             done
-
             rm -f enable.patch
-
             if [[ "$APPLIED" != "true" ]]; then
               echo "⚠️ ERROR: Failed to Apply SUSFS Enable Patch at Any Path Prefix Level"
               exit 1
@@ -2558,32 +2559,25 @@ jobs:
           # TrustyOS Missing Fix (6.6)     
           # Only Run if SUSFS is Enabled
           if [[ "$SUSFSREPOSITORY" != "-1" ]]; then
-
             # Only Apply for 6.6.x Kernel Series
             if [[ "$KV2" == "66" && "$KV3" -le 6630 ]]; then
               echo "🔧 Checking TrustyOS Requirement for Kernel 6.6.x..."
-
               TRUSTYEXISTS=false
-
               # Use Manifest Produced by Extract Manifest Step
               MANIFESTFILE="$GITHUB_WORKSPACE/.repo/manifests_fallback/${FILE}.xml"
-
               # Fallback (Sync Case)
               if [[ ! -s "$MANIFESTFILE" ]]; then
                 MANIFESTFILE="$GITHUB_WORKSPACE/.repo/manifest.xml"
               fi
-
               # Detect Trusty Module in Manifest
               if [[ -f "$MANIFESTFILE" ]] && grep -q "common-modules/trusty" "$MANIFESTFILE"; then
                 TRUSTYEXISTS=true
               fi
-
               # Apply Fix Only if Trusty is Missing          
               if [[ "$TRUSTYEXISTS" == "false" ]]; then
                 echo "🛠 Applying TrustyOS Compatibility Fix (GKI 6.6)"
                 PATCHNAME="$(basename "${SUSFSPATCH:-}")"
                 if [[ -f "$PATCHNAME" ]]; then
-
                  # Patch Adjustments
                   sed -i \
                     's/-32,12 +32,38/-32,11 +32,37/g' \
@@ -2599,8 +2593,8 @@ jobs:
                 echo "✔ TrustyOS Already Present in Manifest, Skipping Fix"
               fi
             fi
-          fi
-                    
+          fi                    
+       
           # SUSFS Meta Fake Patch Workaround
           if [[ "$SUSFSREPOSITORY" != "-1" ]]; then          
             # Patches are Applied Dynamically to Fix
@@ -2616,8 +2610,7 @@ jobs:
             fake_patched_dist=0
             fake_patched_swap=0
             fake_patched_ns=0
-            fake_patched_expand=0  
-            
+            fake_patched_expand=0              
             # Android 15 / Kernel 6.6
             if [ "$KERNELMODULE" = "android15-6.6" ]; then            
               # Restore Missing NR Subpages Definition
@@ -2625,24 +2618,20 @@ jobs:
               if ! grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' \
                 ./fs/proc/task_mmu.c; then
                 echo "⚠️ Missing NR Subpages Definition Detected"
-                echo "🔧 Applying Temporary Task MMU Compatibility Patch"        
-         
+                echo "🔧 Applying Temporary Task MMU Compatibility Patch"                 
                 sed -i \
                   -e '/int ret = 0, copied = 0;/a \\tunsigned int nr_subpages \= __PAGE_SIZE \/ PAGE_SIZE;' \
                   -e '/int ret = 0, copied = 0;/a \\tpagemap_entry_t \*res = NULL;' \
                   ./fs/proc/task_mmu.c          
                 fake_patched=1
               fi
-
               # Add Missing DMA-BUF Header
               if ! grep -qxF '#include <linux/dma-buf.h>' \
                 ./fs/proc/base.c; then
                 echo "⚠️ Missing DMA-BUF Header Detected"
-                echo "🔧 Injecting Required Header"   
-         
+                echo "🔧 Injecting Required Header"            
                 sed -i '/#include <linux\/cpufreq_times.h>/a #include <linux\/dma-buf.h>' ./fs/proc/base.c
               fi
-
               # SUSFS Tree Compatibility Fixes
               # Required for GKI + OKI Trees
               if [[ "$SUSFSVARIANT" == "GKI" || \
@@ -2652,14 +2641,12 @@ jobs:
                   '#include <linux/zswap.h>' \
                   ./mm/memory.c; then          
                   echo "⚠️ Missing ZSwap Header Detected"
-                  echo "🔧 Injecting Required Header"
-          
+                  echo "🔧 Injecting Required Header"         
                   sed -i \
                     '/#include <linux\/sched\/sysctl\.h>/a #include <linux\/zswap.h>' \
                     ./mm/memory.c          
                   fake_patched_swap=1
-                fi
-              
+                fi           
                 # Add Missing Trace / Hooks / FS Header
                 if ! grep -qxF \
                   '#include <trace/hooks/fs.h>' \
@@ -2668,14 +2655,12 @@ jobs:
                   'susfs_def.h' \
                   ./fs/namespace.c; then          
                   echo "⚠️ Missing Trace Hooks Header Detected"
-                  echo "🔧 Injecting Required Header"
-          
+                  echo "🔧 Injecting Required Header"         
                   sed -i \
                     '/#include <trace\/hooks\/blk\.h>/a #include <trace\/hooks\/fs.h>' \
                     ./fs/namespace.c          
                   fake_patched_ns=1
-                fi
-              
+                fi             
                 # Expand Compact OEM if Block
                 # Required for SUSFS Patch Matching
                 if grep -qF \
@@ -2685,8 +2670,7 @@ jobs:
                   'if (vma->vm_end > last_vma_end) {' \
                   ./fs/proc/task_mmu.c; then                
                   echo "⚠️ Compact if Block Detected"
-                  echo "🔧 Expanding Block for SUSFS Compatibility"
-                
+                  echo "🔧 Expanding Block for SUSFS Compatibility"                
                   perl -0777 -i -pe '
                   s@if\s*\(vma->vm_end > last_vma_end\)\s*
                   \s*smap_gather_stats\(vma,\s*&mss,\s*last_vma_end\);@
@@ -2696,8 +2680,8 @@ jobs:
                   fake_patched_expand=1
                 fi
               fi
-            fi
-                    
+            fi                    
+      
             # Android 14 Kernel 6.1 Fix
             if [ "$KERNELMODULE" = "android14-6.1" ]; then
               # Detect Missing VMA Page Logic Support
@@ -2708,14 +2692,12 @@ jobs:
                 echo "🔧 SUSFS Compatibility Workaround Enabled"          
                 fake_patched=1
               fi
-
               # Add Missing DMA-BUF Header
               if ! grep -qxF \
                 '#include <linux/dma-buf.h>' \
                 ./fs/proc/base.c; then         
                 echo "⚠️ Missing DMA-BUF Header Detected"
-                echo "🔧 Injecting Required Header"
-          
+                echo "🔧 Injecting Required Header"          
                 sed -i \
                   '/#include <linux\/cpufreq_times.h>/a #include <linux\/dma-buf.h>' \
                   ./fs/proc/base.c
@@ -2745,8 +2727,7 @@ jobs:
                 '#include <linux/susfs_def.h>' \
                 ./mm/memory.c; then          
                 echo "⚠️ Conflicting swap_slots.h Include Detected"
-                echo "🔧 Removing Conflicting Include"
-          
+                echo "🔧 Removing Conflicting Include"          
                 sed -i \
                   '/#include <linux\/swap_slots\.h>/d' \
                   ./mm/memory.c        
@@ -2757,7 +2738,7 @@ jobs:
             # Revert Temporary Fake Patch
             if [[ "$fake_patched" == 1 ]]; then          
               echo "♻️ Reverting Temporary Fake Patch"          
-              if [[ "$GKIVERSION" == "android15-6.6" ]]; then          
+              if [[ "$KERNELMODULE" == "android15-6.6" ]]; then          
                 if grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' ./fs/proc/task_mmu.c; then
                   sed -i \
                     -e '/unsigned int nr_subpages \= __PAGE_SIZE \/ PAGE_SIZE;/d' \
@@ -2766,9 +2747,9 @@ jobs:
                 fi
               fi
           
-              if [[ "$GKIVERSION" == "android12-5.10" || \
-                    "$GKIVERSION" == "android13-5.15" || \
-                    "$GKIVERSION" == "android14-6.1" ]]; then          
+              if [[ "$KERNELMODULE" == "android12-5.10" || \
+                    "$KERNELMODULE" == "android13-5.15" || \
+                    "$KERNELMODULE" == "android14-6.1" ]]; then          
                 if grep -qxF $'\t\t\tgoto show_pad;' ./fs/proc/task_mmu.c; then
                   sed -i 's/goto show_pad;/return 0;/' ./fs/proc/task_mmu.c
                 fi
@@ -2777,11 +2758,9 @@ jobs:
           fi
           
           # Extract Sublevel
-          SUBLEVEL=$(grep '^SUBLEVEL *=' Makefile | head -n1 | cut -d= -f2 | tr -d ' ')
-          
+          SUBLEVEL=$(grep '^SUBLEVEL *=' Makefile | head -n1 | cut -d= -f2 | tr -d ' ')          
           # Fallback if Empty
-          SUBLEVEL="${SUBLEVEL:-0}"
-          
+          SUBLEVEL="${SUBLEVEL:-0}"          
           # Validate Numeric
           if ! [[ "$SUBLEVEL" =~ ^[0-9]+$ ]]; then
             echo "⚠️ Invalid Sublevel Detected: $SUBLEVEL — Forcing 0"
@@ -2794,15 +2773,12 @@ jobs:
           
           # 5.15 Legacy Fix
           if [[ "$GKIVERSION" == "android13-5.15" && "$SUBLEVEL" -lt 123 ]]; then          
-            LEGACYPATCH="$CURRENTDIR/AndreiMikh-Kernel-Lab/patches/Legacy-5.15-Fix.patch"
-          
+            LEGACYPATCH="$CURRENTDIR/AndreiMikh-Kernel-Lab/patches/Legacy-5.15-Fix.patch"         
             if [[ ! -f "$LEGACYPATCH" ]]; then
               echo "⚠️ Patch Not Found: $LEGACYPATCH"
               exit 1
-            fi
-          
-            echo "🚀 Applying Legacy Fix (Kernel 5.15.0–5.15.123)"
-          
+            fi          
+            echo "🚀 Applying Legacy Fix (Kernel 5.15.0–5.15.123)"          
             # Check if Already Applied
             if patch -R -p1 --dry-run < "$LEGACYPATCH" >/dev/null 2>&1; then
               echo "⚠️ Patch Already Applied — Skipping"
