Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -137,10 +137,9 @@ on:
         type: choice
         description: "Enable LZ4 1.10.0 (6.1 and 6.6) / ZSTD 1.5.7? (6.1) Only if ZRAM (LZ4KD) is Off"
         required: false
-        default: LZ4-1.10.0-Patch
+        default: None
         options:
           - LZ4-1.10.0-Custom-Patch
-          - LZ4-1.10.0+LZ4KD  
           - LZ4-1.10.0-Patch
           - None
         
@@ -2065,7 +2064,6 @@ jobs:
 
           # Clone Required Patch Repositories
           echo "📥 Cloning Dependencies..."
-          git clone --depth=1 https://github.com/SukiSU-Ultra/SukiSU_patch.git || true
           git clone --depth=1 https://github.com/AndreiMikh/AndreiMikh-Kernel-Lab.git || true
 
           echo "✔️ Patch Repositories Cloned"
@@ -2081,12 +2079,12 @@ jobs:
       
           # Detect Kernel Common Directory
           if [[ -d "./kernel_platform/common" ]]; then
-              KDIR="./kernel_platform/common"
+            KDIR="./kernel_platform/common"
           elif [[ -d "./common" ]]; then
-              KDIR="./common"
+            KDIR="./common"
           else
-              echo "⚠️ ERROR: Kernel Common Directory Not Found!"
-              exit 1
+            echo "⚠️ ERROR: Kernel Common Directory Not Found!"
+            exit 1
           fi
       
           echo "📁 Kernel Directory: $KDIR"
@@ -2099,11 +2097,13 @@ jobs:
       
           if [[ "$SUSFSVARIANT" == "OGKI" ]]; then
             BRANCH="oki-${ANDROIDVERSION}-${KERNELVERSION}"
+         
             if [[ "$SUSFSBRANCHDEV" == "true" ]]; then
               BRANCH="${BRANCH}-dev"
             fi
             git clone --depth=1 https://github.com/cctv18/susfs4oki.git susfs4ksu -b "$BRANCH"
-          else
+      
+          else           
             if [[ "$SUSFSBRANCHDEV" == "true" ]]; then
               BRANCH="${BRANCH}-dev"
             fi
