Update Main V4.yml

diff --git a/.github/workflows/Main V4.yml b/.github/workflows/Main V4.yml
--- a/.github/workflows/Main V4.yml
+++ b/.github/workflows/Main V4.yml
@@ -1615,12 +1615,9 @@ jobs:
                 sed -i '/#include <linux\/cpufreq_times.h>/a #include <linux\/dma-buf.h>' ./fs/proc/base.c
               fi
 
-              # Add Fix for SUSFS for KSU Patch
-              if [[ "${{ github.event.inputs.SUSFS_VERSION }}" == "GKI" && \
-                    "${{ github.event.inputs.SUSFS_VERSION }}" == "OGKI" && \
-                    "${{ github.event.inputs.KSU_META }}" == "SukiSU-Ultra" ]] && \
-                 ! grep -qxF '#include <linux/susfs.h>' ./fs/proc/base.c; then
-                echo "SUSFS_VERSION=GKI & KSU Meta=ReSukiSU, Missing SUSFS Header, Adding Fix..."
+              # Add Fix for SUSFS for KSU Patch         
+              if ! grep -qxF '#include <linux/susfs.h>' ./fs/proc/base.c; then
+                echo ""Missing #include <linux/susfs.h>, Missing SUSFS Header, Adding Fix..."
 
                 sed -i '/#include <linux\/dma-buf.h>/a #include <linux\/susfs.h>' ./fs/proc/base.c
               fi
