Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -4408,19 +4408,38 @@ jobs:
 
           cd ./common
 
-          # Resolve Physical Source Paths
-          COMMONREALPATH=$(pwd -P)
-          KERNELPLATFORMREALPATH=$(dirname "$COMMONREALPATH")
-          ROOTREALPATH=$(dirname "$KERNELPLATFORMREALPATH")
+          # Resolve Physical Root Path
+          if ! ROOTREALPATH=$(realpath ../..); then
+            echo "⚠️ Real Path Failed"
+            fallback "realpath"
+          fi
+
+          ROOTREALPATH="${ROOTREALPATH%/}"
 
           # Configure Reproducible Compiler Path Mapping
           MAP="-fdebug-prefix-map=$ROOTREALPATH=."
           MPMAP="-fmacro-prefix-map=$ROOTREALPATH=."
           FPMAP="-ffile-prefix-map=$ROOTREALPATH=."
 
-          # Kernel Compiler Flags
-          KCFLAGS="$MAP $FPMAP -no-canonical-prefixes -O2 -pipe -Wno-error -fno-stack-protector -D__ANDROID_COMMON_KERNEL__"      
-          KCPPFLAGS="$MPMAP"
+          # Build KCFLAGS as Array Structured
+          KCFLAGS=(
+            "$MAP"
+            "$FPMAP"
+            -no-canonical-prefixes
+            -Wno-error
+            -O2
+            -pipe
+            -D__ANDROID_COMMON_KERNEL__
+          )
+
+          # Build KCPPFLAGS as Array Structured
+          KCPPFLAGS=(
+            "$MPMAP"
+          )
+
+          # Convert Compiler Flags to Space-Separated Strings for Make
+          KCFLAGS="${KCFLAGS[*]}"
+          KCPPFLAGS="${KCPPFLAGS[*]}"
 
           # Create Compiler Cache CCache Wrapper
           REALCLANGBIN="$CLANGFULLPATH"
@@ -4470,7 +4489,7 @@ jobs:
 
           # Generate GKI Default Configuration
           echo ">> 🚀 Running GKI Default Configuration"
-          if ! make O=out "${MAKE_ARGS[@]}" gki_defconfig --no-print-directory; then
+          if ! make O=out ARCH=arm64 "${MAKE_ARGS[@]}" gki_defconfig; then
             echo "⚠️ GKI Default Configuration Failed"
             fallback "gkidefconfigfailed"
           fi
