Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -5434,28 +5434,27 @@ jobs:
 
           # Define Paths
           WS="${GITHUB_WORKSPACE}/kernel_workspace"
-          KDIR="${WS}/kernel_platform/common"
+          NOMOUNTSOURCE="${WS}/nomount-source"
           NOMOUNTBIN="${WS}/nomount-bin"
           NOMOUNTMODULEDIR="${WS}/nomount-metamodule"
           NOMOUNTOUTDIR="${WS}/output"
-
-          # Resolve the NoMount Kernel Source
-          [[ -L "$KDIR/fs/nomount" ]] || {
-            echo "⚠️ NoMount SymLink Missing"
-            exit 1
-          }
-
-          NOMOUNTKDIR="$(readlink -f "$KDIR/fs/nomount")"
-          NOMOUNTROOT="$(dirname "$NOMOUNTKDIR")"
-          NOMOUNTMODULESRC="${NOMOUNTROOT}/module"
+          NOMOUNTMODULESRC="${NOMOUNTSOURCE}/module"
 
           echo "------------------------------"
           echo "NoMount Metamodule Packaging"
           echo "------------------------------"
-          echo "📂 NoMount Root   : $NOMOUNTROOT"
+          echo "📂 NoMount Source : $NOMOUNTSOURCE"
           echo "📂 Module Source  : $NOMOUNTMODULESRC"
+          echo "📂 Binary Source  : $NOMOUNTBIN"
           echo "📂 Output         : $NOMOUNTOUTDIR"
           echo ""
+
+          # Verify NoMount Source
+          [[ -d "$NOMOUNTSOURCE" ]] || {
+            echo "⚠️ NoMount Source Directory Missing:"
+            echo "   $NOMOUNTSOURCE"
+            exit 1
+          }
 
           # Verify NoMount Module Source
           [[ -d "$NOMOUNTMODULESRC" ]] || {
@@ -5497,11 +5496,8 @@ jobs:
             "$NOMOUNTMODULEDIR/bin/nm-arm"
 
           # Identify Exact NoMount Source Commit
-          if git -C "$NOMOUNTROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
-            NOMOUNTCOMMIT="$(git -C "$NOMOUNTROOT" rev-parse HEAD)"
-          else
-            NOMOUNTCOMMIT="Unknown"
-          fi
+          NOMOUNTCOMMIT="$(git -C "$NOMOUNTSOURCE" rev-parse HEAD)"
+          echo "📌 NoMount Commit: $NOMOUNTCOMMIT"
 
           # Record NoMount Source Commit
           printf '%s\n' "$NOMOUNTCOMMIT" \
@@ -5515,13 +5511,14 @@ jobs:
 
           # Define Package Name
           NOMOUNTMODULEZIP="${NOMOUNTOUTDIR}/NoMount-${NOMOUNTCOMMIT}.zip"
+
           # Remove Existing Package
           rm -f "$NOMOUNTMODULEZIP"
 
           # Package Metamodule
           echo "📦 Creating NoMount MetaModule..."
           (
-            cd "$NOMOUNTMODULEZIP"
+            cd "$NOMOUNTMODULEDIR"
             zip -qr "$NOMOUNTMODULEZIP" .
           )
 
@@ -5544,7 +5541,7 @@ jobs:
           echo ""
           echo "📁 Contents:"
           unzip -l "$NOMOUNTMODULEZIP"
-         
+
           echo ""
           echo "🎉 NoMount MetaModule Packaged Successfully"
 
