Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -3139,13 +3139,31 @@ jobs:
         shell: bash
         run: |
           set -Eeuo pipefail
-          # NoMount-Suite paths
+          # NoMount-Suite Paths          
           NMSUITEDIR="${WORKSPACEDIR}/NoMount-Suite"
           NMSUITEKERNELPATCHESFOLDER="${WORKSPACEDIR}/nmsuitekernelpatches"
-          echo "🫥 NoMount-Suite Kernel Integration"
+          echo "└─ 🫥 NoMount-Suite Kernel Integration"
           echo "└─ Kernel Source : ${COMMONKERNELFOLDER}"
           echo "└─ Kernel Version: ${KERNELVERSION}"
           echo "└─ Defconfig     : ${DEFCONFIG}"        
+
+          # Root Engine Directory
+          ROOTENGINE="${{ inputs.ROOTENGINE }}"
+          case "$ROOTENGINE" in
+            SukiSU-Ultra|BakaSU|KernelSU)
+              KSUFOLDER="$KERNELPLATFORM/KernelSU"
+              ;;
+            KernelSU-Next)
+              KSUFOLDER="$KERNELPLATFORM/KernelSU-Next"
+              ;;
+            *)
+              echo "└─ ⚠️ [Error] Unsupported Root Engine: $ROOTENGINE"
+              exit 1
+              ;;
+          esac
+          echo "└─ 📂 [Info] Root Engine Directory : $KSUFOLDER"
+          echo "KSUFOLDER=$KSUFOLDER" >> "$GITHUB_ENV"
+          
           # Apply Patch Safely
           applypatch() {
             local patchfile="$1"
@@ -3271,10 +3289,10 @@ jobs:
               -print |
             sort
           )
-          if [[ -n "${KSU_FOLDER:-}" ]]; then
+          if [[ -n "${KSUFOLDER:-}" ]]; then
             KSUSEQNOPATCH="${HOOKDIR}/fix_selinux_seqno.patch"
             if [[ -f "${KSUSEQNOPATCH}" ]]; then
-              applypatch "${KSUSEQNOPATCH}" "${KSU_FOLDER}"
+              applypatch "${KSUSEQNOPATCH}" "${KSUFOLDER}"
             fi
           else
             echo "└─ ⚠️ KSU Directory is Not Set; Skipping KSU Seqno Patch"
