Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -3543,7 +3543,7 @@ jobs:
           [[ -f "$KCONFIGFILE" ]] || { echo "⚠️ Missing Kernel Configuration"; exit 1; }
           [[ -f "$MAKEFILE" ]] || { echo "⚠️ Missing Makefile"; exit 1; }
 
-          # Clone Repository (Shallow)
+          # Clone Repository
           if [[ ! -d "$RKREPODIR/.git" ]]; then
             echo "📩 Cloning ReKernel Repository..."
             git clone --depth=1 https://github.com/Sakion-Team/Re-Kernel.git "$RKREPODIR"
@@ -3596,17 +3596,24 @@ jobs:
           echo "♻️ All Re-Kernel Files and Directories Synced!"
 
           # Update Build Bazel (GKI)
-          BUILDBAZEL="${WS}/kernel_platform/common/BUILD.bazel"          
+          BUILDBAZEL="${WS}/kernel_platform/common/BUILD.bazel"
+          
           if [[ -f "$BUILDBAZEL" ]]; then
             if grep -q 'drivers/rekernel/rekernel\.ko' "$BUILDBAZEL"; then
               echo "⚠️ Build Bazel Already Patched"
             else
-              echo "➕ Patching Build Bazel..."          
+              echo "⚙️ Patching Build Bazel..."
+          
               sed -i \
-                '/"kernel_aarch64": {/,/"kernel_aarch64_16k": {/ s|"module_implicit_outs": get_gki_modules_list("arm64")|"module_implicit_outs": get_gki_modules_list("arm64") + ["drivers/rekernel/rekernel.ko"]|' \
+                '0,/name = "kernel_aarch64",/{/module_implicit_outs/s|,$| + ["drivers/rekernel/rekernel.ko"],|}' \
                 "$BUILDBAZEL"
           
-              echo "✔️ Build Bazel Patched"
+              if grep -q 'drivers/rekernel/rekernel\.ko' "$BUILDBAZEL"; then
+                echo "🚀 Build Bazel Patched"
+              else
+                echo "⚠️ Failed to Patch Build Bazel"
+                exit 1
+              fi
             fi
           else
             echo "ℹ️ Build Bazel Not Found, Skipping..."
