Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -879,63 +879,12 @@ jobs:
             CCache-${{ runner.os }}-${{ env.MANIFESTBASEFILE }}-${{ env.CPUD }}-
             CCache-${{ runner.os }}-${{ env.MANIFESTBASEFILE }}-
             CCache-${{ runner.os }}-
-            
-      # ==============================
-      # Release Cache Restoration
-      # ==============================
-      - name: 🔧 Release Cache Restoration
-        id: cache-restoration
-        if: ${{ env.BUILDCCACHE != 'Disabled' && steps.ccache-restore.outputs.cache-hit != 'true' }}
-        run: |
-          set -e
-
-          echo "------------------------------"  
-          echo "🚀 Cache Not Found Locally, Attempting to Restore from GitHub Release..."
-          echo "------------------------------"
-          echo ""
-      
-          # Define the Release Asset
-          TAR="CCache-${{ runner.os }}-${{ env.MANIFESTBASEFILE }}-${{ env.CPUD }}-${{ github.ref_name }}.tar.zst"
-      
-          # Build the Download URL
-          URL="https://github.com/AndreiMikh/CCache/releases/download/001/${TAR}"
-          echo "📩 Downloading from: $URL"
-      
-          # Ensure Cache Directory Exists
-          mkdir -p "${{ env.CCACHE_DIR }}"
-          chmod -R 775 "${{ env.CCACHE_DIR }}"
-      
-          # Download Cache
-          if ! curl -fsSL -o "$TAR" "$URL"; then
-            echo "⚠️ Cache Not Found, Skipping Restore..."
-            echo "cache-restored=false" >> $GITHUB_OUTPUT
-            exit 0
-          fi
-      
-          echo "🔥 Cache Found, Extracting..."
-      
-          # Extract
-          if [ -f "$TAR" ]; then
-            tar -I zstd -xvf "$TAR" -C "${{ env.CCACHE_DIR }}"
-          else
-            echo "⚠️ Archive Missing after Download"
-            echo "cache-restored=false" >> $GITHUB_OUTPUT
-            exit 0
-          fi
-      
-          # Validate Extraction
-          if [[ -n "$(ls -A "${CCACHE_DIR}" 2>/dev/null)" ]]; then
-            echo "👾 Cache Successfully Restored"
-            echo "cache-restored=true" >> $GITHUB_OUTPUT
-          else
-            echo "⚠️ Cache Extraction Failed"
-            echo "cache-restored=false" >> $GITHUB_OUTPUT
-          fi
 
       # ==============================
       # Cache ECS System
       # ==============================
       - name: 🔧 Cache ECS System
+        if: ${{ env.BUILDCCACHE != 'Disabled' && steps.ccache-restore.outputs.cache-hit != 'true' }}
         shell: bash
         run: |
           set -euo pipefail
@@ -990,7 +939,6 @@ jobs:
           else
             echo "⚠️ Custom Compiler Cache Binary Not Found, Skipping Override"
           fi
-          # -------------------------------------------
       
           echo "📦 Overridden Compiler Cache: $(which ccache)"
           ccache --version
@@ -1041,6 +989,58 @@ jobs:
 
           echo ""
           echo "🎉 Cache ECS Setup Complete"
+            
+      # ==============================
+      # Release Cache Restoration
+      # ==============================
+      - name: 🔧 Release Cache Restoration
+        id: cache-restoration
+        if: ${{ env.BUILDCCACHE != 'Disabled' && steps.ccache-restore.outputs.cache-hit != 'true' }}
+        run: |
+          set -e
+
+          echo "------------------------------"  
+          echo "🚀 Cache Not Found Locally, Attempting to Restore from GitHub Release..."
+          echo "------------------------------"
+          echo ""
+      
+          # Define the Release Asset
+          TAR="CCache-${{ runner.os }}-${{ env.MANIFESTBASEFILE }}-${{ env.CPUD }}-${{ github.ref_name }}.tar.zst"
+      
+          # Build the Download URL
+          URL="https://github.com/AndreiMikh/CCache/releases/download/001/${TAR}"
+          echo "📩 Downloading from: $URL"
+      
+          # Ensure Cache Directory Exists
+          mkdir -p "${{ env.CCACHE_DIR }}"
+          chmod -R 775 "${{ env.CCACHE_DIR }}"
+      
+          # Download Cache
+          if ! curl -fsSL -o "$TAR" "$URL"; then
+            echo "⚠️ Cache Not Found, Skipping Restore..."
+            echo "cache-restored=false" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+      
+          echo "🔥 Cache Found, Extracting..."
+      
+          # Extract
+          if [ -f "$TAR" ]; then
+            tar -I zstd -xvf "$TAR" -C "${{ env.CCACHE_DIR }}"
+          else
+            echo "⚠️ Archive Missing after Download"
+            echo "cache-restored=false" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+      
+          # Validate Extraction
+          if [[ -n "$(ls -A "${CCACHE_DIR}" 2>/dev/null)" ]]; then
+            echo "👾 Cache Successfully Restored"
+            echo "cache-restored=true" >> $GITHUB_OUTPUT
+          else
+            echo "⚠️ Cache Extraction Failed"
+            echo "cache-restored=false" >> $GITHUB_OUTPUT
+          fi
   
       # ==============================
       # Configure and Setup Compiler Cache
