Update Main Kernel Builder.yml

diff --git a/.github/workflows/Main Kernel Builder.yml b/.github/workflows/Main Kernel Builder.yml
--- a/.github/workflows/Main Kernel Builder.yml
+++ b/.github/workflows/Main Kernel Builder.yml
@@ -2093,9 +2093,14 @@ jobs:
           PDIR="${GITHUB_WORKSPACE}/kernel_workspace/AndreiMikh-Kernel-Lab/scripts"
           WORKDIR="${GITHUB_WORKSPACE}/kernel_workspace/kernel_platform/common"
           SCRIPT="${PDIR}/FakePatches.kts"
+          
+          # Kotlin Environment
+          KOTLINHOME="${KOTLINHOME:-$HOME/kotlinc}"
+          KOTLINC="${KOTLINHOME}/bin/kotlinc"
 
           echo "📌 Script   : $SCRIPT"
           echo "📌 Work Dir : $WORKDIR"
+          echo "📌 Compiler : $KOTLINC"
 
           [[ -f "$SCRIPT" ]] || {
             echo "⚠️ FakePatches Kotlin Script Not Found"
@@ -2107,6 +2112,12 @@ jobs:
             exit 1
           }
 
+          [[ -x "$KOTLINC" ]] || {
+            echo "⚠️ Kotlin Compiler Not Found or Not Executable: $KOTLINC"
+            exit 1
+          }
+
+          # Verify Kotlin
           echo "☕ Kotlin Compiler:"
           "$KOTLINC" -version
 
@@ -2479,8 +2490,13 @@ jobs:
           WORKDIR="${GITHUB_WORKSPACE}/kernel_workspace/kernel_platform/common"
           SCRIPT="${PDIR}/FakePatches.kts"
 
+          # Kotlin Environment
+          KOTLINHOME="${KOTLINHOME:-$HOME/kotlinc}"
+          KOTLINC="${KOTLINHOME}/bin/kotlinc"
+
           echo "📌 Script   : $SCRIPT"
           echo "📌 Work Dir : $WORKDIR"
+          echo "📌 Compiler : $KOTLINC"
 
           [[ -f "$SCRIPT" ]] || {
             echo "⚠️ FakePatches Kotlin Script Not Found"
@@ -2492,6 +2508,12 @@ jobs:
             exit 1
           }
 
+          [[ -x "$KOTLINC" ]] || {
+            echo "⚠️ Kotlin Compiler Not Found or Not Executable: $KOTLINC"
+            exit 1
+          }
+
+          # Verify Kotlin
           echo "☕ Kotlin Compiler:"
           "$KOTLINC" -version
 
