Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -2702,6 +2702,7 @@ jobs:
                 https://raw.githubusercontent.com/AndreiMikh/AndreiMikh-Kernel-Lab/LiquidAndrei/lz4accel.h
               curl -L -o "$F2FS/lz4armv8.S" \
                 https://raw.githubusercontent.com/AndreiMikh/AndreiMikh-Kernel-Lab/LiquidAndrei/lz4armv8.S
+         
               echo "✔️ LZ4 ARMv8 Sources Ready"
             fi
           fi
@@ -2731,11 +2732,11 @@ jobs:
 
             # Apply Patch Using Git Apply
             if [[ "$PATCHNAME" == "001-lz4.patch" ]]; then
-              git apply --ignore-whitespace -p1 < "$PATCHFILE" || echo "⚠️ Patch Failed, but Continuing..."
-              echo "✔️ Patch Applied"
+              git apply --ignore-whitespace -p1 < "$PATCHFILE" || echo "⚠️ $PATCHNAME Patch Failed, but Continuing..."
+              echo "✔️ $PATCHNAME Patch Applied"
             else
-              patch --ignore-whitespace -p1 < "$PATCHFILE" || echo "⚠️ Patch Failed, but Continuing..."
-              echo "✔️ Patch Applied"
+              patch --ignore-whitespace -p1 < "$PATCHFILE" || echo "⚠️ $PATCHNAME Patch Failed, but Continuing..."
+              echo "✔️ $PATCHNAME Patch Applied"
             fi
           }
 
