Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -232,7 +232,7 @@ on:
         type: choice
         description: "Performance = (XUS - Enabled | Space Clean - Disabled | Compiler Cache - Enabled)"
         required: true
-        default: Performance
+        default: Balance
         options:
           - Performance
           - Balance
@@ -2230,18 +2230,43 @@ jobs:
               echo "⚠️ Hide Patch Skipped (Unsupported Base)"
             fi
 
-            # SUSFS 10 Enable Patch for KernelSU
-            if [[ "$ROOTENGINE" == "KernelSU" ]]; then      
-              echo "⚙️ SUSFS 10 Enable Patch..."
-      
-              URL="https://gitlab.com/simonpunk/susfs4ksu/-/raw/${BRANCH}/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch"      
-              wget -q "$URL" -O enable.patch || true
-      
+            # SUSFS 10 Enable Patch for KernelSU (ONLY for KernelSU)
+            if [[ "$ROOTENGINE" == "KernelSU" ]]; then
+
+              echo "⚙️ Applying KernelSU SUSFS enable patch"
+
+              if [[ "$SUSFSVARIANT" == "OGKI" ]]; then
+                PATCHBRANCH="oki-${ANDROIDVERSION}-${KERNELVERSION}"
+              else
+                PATCHBRANCH="gki-${ANDROIDVERSION}-${KERNELVERSION}"
+              fi
+
+              [[ "${SUSFSBRANCHDEV:-}" == "true" ]] && PATCHBRANCH="${PATCHBRANCH}-dev"
+
+              case "$SUSFSVARIANT" in
+                GKI)
+                  SUSFS10URL="https://gitlab.com/simonpunk/susfs4ksu/-/raw/${PATCHBRANCH}/kernel_patches/${ROOTENGINE}/10_enable_susfs_for_ksu.patch"
+                  ;;
+                OGKI)
+                  SUSFS10URL="https://raw.githubusercontent.com/cctv18/susfs4oki/${PATCHBRANCH}/kernel_patches/${ROOTENGINE}/10_enable_susfs_for_ksu.patch"
+                  ;;
+                *)
+                  echo "⚠️ Invalid SUSFS Variant"
+                  exit 1
+                  ;;
+              esac
+
+              wget -q "$SUSFS10URL" -O enable.patch || true
+
               if [[ -f enable.patch ]]; then
                 for pathprefix in 0 1 2; do
                   patch -p$pathprefix < enable.patch && break || true
                 done
+                rm -f enable.patch
               fi
+
+            else
+              echo "⚠️ Skipping KernelSU SUSFS Enable Patch (Root = $ROOTENGINE Not Compatible)"
             fi
             
             # Revert Temporary Fake Patch
