Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -5049,15 +5049,26 @@ jobs:
           echo "📥 Fetching Latest KernelPatch-Next Release..."
 
           KPREPO="KernelSU-Next/KPatch-Next"
-          URLAPI="https://api.github.com/repos/$KPREPO/releases/latest"
+      
+          # Try Latest Release API
+          LATESTJSON=$(curl -fsSL "https://api.github.com/repos/$KPREPO/releases/latest" || true)
 
-          JSON=$(curl -s "$URLAPI")
+          TAG=$(echo "$LATESTJSON" | grep '"NAMETAG"' | head -n 1 | cut -d '"' -f 4)
 
           # Get Latest Tag
-          TAG=$(echo "$JSON" | grep '"tag_name"' | head -n 1 | cut -d '"' -f 4)
+          # 2. Fallback: Releases List
+          if [[ -z "$TAG" || "$TAG" == "null" ]]; then
+            echo "⚠️ Releases Latest Failed or Cannot be Found → Falling Back to Full Releases List..."
 
-          if [[ -z "$TAG" ]]; then
-            echo "⚠️ Failed to Fetch Latest Tag"
+            TAG=$(curl -fsSL "https://api.github.com/repos/$KPREPO/releases" \
+              | grep '"NAMETAG"' \
+              | head -n 1 \
+              | cut -d '"' -f 4)
+          fi
+         
+          # Final Check
+          if [[ -z "$TAG" || "$TAG" == "null" ]]; then
+            echo "⚠️ Failed to Resolve KernelPatch-Next Tag"
             exit 1
           fi
 
@@ -5070,7 +5081,7 @@ jobs:
           URLKPIMG="$BASE/kpimg-linux"
 
           echo "------------------------------"
-          echo "📦 KernelPatch-Next Latest Tag : $URLKPIMG"
+          echo "📦 KernelPatch-Next Latest Tag : $TAG"
           echo "📦 KernelPatch-Next KPTools    : $URLKPTOOLS"
           echo "📦 KernelPatch-Next KPImg      : $URLKPIMG"
           echo "------------------------------"          
