Update Main Version 2.0.yml

diff --git a/.github/workflows/Main Version 2.0.yml b/.github/workflows/Main Version 2.0.yml
--- a/.github/workflows/Main Version 2.0.yml
+++ b/.github/workflows/Main Version 2.0.yml
@@ -1891,11 +1891,11 @@ jobs:
           curl -fsSL -o "${PATCH_FILE}" "${PATCH_URL}" || { echo "❌ Failed to Download Patch File"; exit 11; }
 
           # ==============================
-          # Apply Patch 
+          # Apply Patch
           # ==============================
           echo "Applying Fengchi Patch..."
           dos2unix "${PATCH_FILE}" || true
-          patch -p1 -F 3 --forward < "${PATCH_FILE}" || { echo "❌ Failed to Apply Patch"; exit 12; }
+          patch -p1 -F 3 < "${PATCH_FILE}" || { echo "❌ Failed to Apply Patch"; exit 12; }
           echo "✅ Fengchi Patch Applied"
 
           # ==============================
