Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -2643,10 +2643,11 @@ jobs:
           echo "🎉 SukiSU ZRAM Patch Process Completed"
 
       # ==============================
-      # LZ4 1.10.0 / ZSTD 1.5.7 Patches
+      # LZ4 1.10.0 / ZSTD 1.5.7 Setup
       # ==============================
-      - name: 🔧 LZ4 1.10.0 / ZSTD 1.5.7 Patches
+      - name: 🔧 LZ4 1.10.0 / ZSTD 1.5.7 Setup
         if: ${{ github.event.inputs.ZRAMCUSTOMPATCH == 'LZ4-1.10.0-Patch' || github.event.inputs.ZRAMCUSTOMPATCH == 'LZ4-1.10.0-Custom-Patch' }}
+        shell: bash 
         run: |
           set -euo pipefail
 
@@ -2667,7 +2668,7 @@ jobs:
           XMPATCH="${GITHUB_WORKSPACE}/kernel_workspace/kernel_patches/zram_patches"
         
           echo "------------------------------"
-          echo "📌 LZ4 and ZSTD Setup Stage"
+          echo "🚀 LZ4 1.10.0 / ZSTD 1.5.7 Setup..."
           echo "📁 Kernel Version  : $KERNELVERSION"
           echo "------------------------------"
           echo ""
@@ -2699,11 +2700,11 @@ jobs:
 
             # Apply Patch Using Git Apply
             if [[ "$PATCHNAME" == "001-lz4.patch" ]]; then
-              git apply --ignore-whitespace -p1 < "$PATCHFILE" || echo "⚠️ $PATCHNAME Failed, but Continuing..."
-              echo "✔️ $PATCHNAME Applied"
+              git apply --ignore-whitespace -p1 < "$PATCHFILE" || echo "⚠️ Patch Failed, but Continuing..."
+              echo "✔️ Patch Applied"
             else
-              patch --ignore-whitespace -p1 < "$PATCHFILE" || echo "⚠️ $PATCHNAME Failed, but Continuing..."
-              echo "✔️ $PATCHNAME Applied"
+              patch --ignore-whitespace -p1 < "$PATCHFILE" || echo "⚠️ Patch Failed, but Continuing..."
+              echo "✔️ Patch Applied"
             fi
           }
 
