Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -302,7 +302,7 @@ jobs:
       CCACHE_BASEDIR: ${{ github.workspace }}
       
       # Kernel Builds
-      CCACHE_COMPILERCHECK: none
+      CCACHE_COMPILERCHECK: content
       CCACHE_NOHASHDIR: true
       CCACHE_NOHARDLINK: true
 
@@ -1027,19 +1027,12 @@ jobs:
           echo "🚀 Using Compiler Cache at $CCACHE_DIR..."          
           
           # Set Cache Size 
-          ccache -M "${CCACHE_MAXSIZE:-10G}"
+          ccache -M "${{ env.CCACHE_MAXSIZE }}"
 
-          # Core Cache Optimizations 
-          ccache --set-config=base_dir="$GITHUB_WORKSPACE"
-          ccache --set-config=hash_dir=false
-          ccache --set-config=compiler_check=none
-
-          # Cache Performance Boost
-          ccache --set-config=compression=false
-          ccache --set-config=direct_mode=true
-
-          # Improve Hit Rate (Safe Looseness) for Cache
-          ccache --set-config=sloppiness=file_macro,time_macros
+          export CCACHE_COMPILERCHECK="${{ env.CCACHE_COMPILERCHECK }}" || echo "⚠️ Compiler Check Not Found"
+          export CCACHE_BASEDIR="${{ env.CCACHE_BASEDIR }}" || echo "⚠️ Base Directory Not Found"
+          export CCACHE_NOHASHDIR="${{ env.CCACHE_NOHASHDIR }}" || echo "⚠️ NoHash Directory Not Found"
+          export CCACHE_NOHARDLINK="${{ env.CCACHE_NOHARDLINK }}" || echo "⚠️ Cache Hardlink Not Found"    
           
           # Make Compiler Cache Global for System Cache
           export PATH="/usr/lib/ccache:$PATH"
