Update Main V4.yml

diff --git a/.github/workflows/Main V4.yml b/.github/workflows/Main V4.yml
--- a/.github/workflows/Main V4.yml
+++ b/.github/workflows/Main V4.yml
@@ -1542,6 +1542,13 @@ jobs:
 
                 sed -i '/#include <linux\/cpufreq_times.h>/a #include <linux\/dma-buf.h>' ./fs/proc/base.c
               fi
+
+              # Add Fix for SUSFS for KSU Patch
+              if ! grep -qxF '#include <linux/susfs.h>' ./fs/proc/base.c; then
+                echo "Missing SUSFS Header, Adding a Fix..."
+
+                sed -i '/#include <linux\/dma-buf.h>/a #include <linux\/susfs.h>' ./fs/proc/base.c
+              fi 
             fi
 
             # ==============================
