Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -2387,53 +2387,31 @@ jobs:
             fake_patched_expand=0                                      
             # Android 15 / Kernel 6.6 Postfix Compatibility Fixes
             if [ "$KERNELMODULE" = "android15-6.6" ]; then
+              if (( SUBLEVEL <= 30 )); then
               # Restore Missing NR Subpages Definition
               # Required by Newer SUSFS Patches
-              if ! grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' \
-                ./fs/proc/task_mmu.c; then            
-                echo "⚠️ Missing NR Subpages Definition Detected"
-                echo "🔧 Applying Temporary Task MMU Compatibility Patch"            
-                sed -i \
-                  -e '/int ret = 0, copied = 0;/a \\tunsigned int nr_subpages \= __PAGE_SIZE \/ PAGE_SIZE;' \
-                  -e '/int ret = 0, copied = 0;/a \\tpagemap_entry_t \*res = NULL;' \
-                  ./fs/proc/task_mmu.c           
-                fake_patched=1
+                if ! grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' \
+                  ./fs/proc/task_mmu.c; then            
+                  echo "⚠️ Missing NR Subpages Definition Detected"
+                  echo "🔧 Applying Temporary Task MMU Compatibility Patch"            
+                  sed -i \
+                    -e '/int ret = 0, copied = 0;/a \\tunsigned int nr_subpages \= __PAGE_SIZE \/ PAGE_SIZE;' \
+                    -e '/int ret = 0, copied = 0;/a \\tpagemap_entry_t \*res = NULL;' \
+                    ./fs/proc/task_mmu.c           
+                  fake_patched=1
+                fi
               fi
             
               # Add Missing DMA-BUF Header
-              if ! grep -qxF '#include <linux/dma-buf.h>' \
-                ./fs/proc/base.c; then            
-                echo "⚠️ Missing DMA-BUF Header Detected"
-                echo "🔧 Injecting Required Header"            
-                sed -i \
-                  '/#include <linux\/cpufreq_times.h>/a #include <linux\/dma-buf.h>' \
-                  ./fs/proc/base.c
-              fi
-
-              # Add Missing SUSFS Header
-              if [[ -f ./include/linux/susfs_def.h ]]; then              
-                # Skip if SUSFS Header has Already been Included
-                if ! grep -qF '#include <linux/susfs_def.h>' ./fs/proc/base.c; then              
-                  # Verify Expected Insertion Point Exists Before Modifying File
-                  if grep -qF '#include <linux/dma-buf.h>' ./fs/proc/base.c; then
-                    echo "⚠️ Missing SUSFS Header Detected"
-                    echo "🔧 Injecting Required SUSFS Header..."              
-                    sed -i '/#include <linux\/dma-buf.h>/a\
-              #if defined(CONFIG_KSU_SUSFS_SUS_MAP) || defined(CONFIG_KSU_SUSFS_OPEN_REDIRECT)\
-              #include <linux/susfs_def.h>\
-              #endif' ./fs/proc/base.c              
-                    echo "☘️ SUSFS Header Successfully Injected"
-                  else
-                    echo "⚠️ Injection Point (Linux / DMA-BUF Headers) Not Found"
-                    echo "⏭️ Skipping SUSFS Header Injection"
-                  fi
-              
-                else
-                  echo "☘️ SUSFS Header Already Present"
-                fi              
-              else
-                echo "⚠️ SUSFS Header Not Found"
-                echo "⏭️ Skipping SUSFS Header Injection"
+              if (( SUBLEVEL <= 92 )); then
+                if ! grep -qxF '#include <linux/dma-buf.h>' \
+                  ./fs/proc/base.c; then            
+                  echo "⚠️ Missing DMA-BUF Header Detected"
+                  echo "🔧 Injecting Required Header"            
+                  sed -i \
+                    '/#include <linux\/cpufreq_times.h>/a #include <linux\/dma-buf.h>' \
+                    ./fs/proc/base.c
+                fi
               fi
 
               # VMA Pad Start Compatibility
@@ -2471,10 +2449,9 @@ jobs:
                 fi
               fi
             
-              # SUSFS Tree Compatibility Fixes
+              # SUSFS Tree Compatibility Fixes Sublevel 57
               # GKI / OGKI Tree Compatibility
-              if [[ "$SUSFSVARIANT" == "GKI" || \
-                    "$SUSFSVARIANT" == "OGKI" ]]; then           
+              if (( SUBLEVEL <= 57 )); then           
                 # Inject Missing ZSwap Header
                 if ! grep -qxF '#include <linux/zswap.h>' ./mm/memory.c; then            
                   echo "⚠️ Missing ZSwap Header Detected"
@@ -2486,14 +2463,16 @@ jobs:
                 fi
             
                 # Add Missing Trace / Hooks / FS Header
-                if ! grep -qxF '#include <trace/hooks/fs.h>' ./fs/namespace.c && \
-                   ! grep -qF 'susfs_def.h' ./fs/namespace.c; then            
-                  echo "⚠️ Missing Trace Hooks Header Detected"
-                  echo "🔧 Injecting Required Header..."            
-                  sed -i \
-                    '/#include <trace\/hooks\/blk\.h>/a #include <trace\/hooks\/fs.h>' \
-                    ./fs/namespace.c            
-                  fake_patched_ns=1
+                if (( SUBLEVEL <= 30 )); then
+                  if ! grep -qxF '#include <trace/hooks/fs.h>' ./fs/namespace.c && \
+                     ! grep -qF 'susfs_def.h' ./fs/namespace.c; then            
+                    echo "⚠️ Missing Trace Hooks Header Detected"
+                    echo "🔧 Injecting Required Header..."            
+                    sed -i \
+                      '/#include <trace\/hooks\/blk\.h>/a #include <trace\/hooks\/fs.h>' \
+                      ./fs/namespace.c            
+                    fake_patched_ns=1
+                  fi
                 fi
             
                 # Expand Compact OEM if Block
