Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -2521,12 +2521,25 @@ jobs:
             fi          
           
             # Android 12 / 13 Fix
-            if [[ "$GKIVERSION" == "android12-5.10" || "$GKIVERSION" == "android13-5.15" ]]; then          
-              if ! grep -qxF $'\tif (!vma_pages(vma))' ./fs/proc/task_mmu.c; then
-                echo "🛠️ Missing VMA Pages Fix"
+            if [[ "$GKIVERSION" == "android12-5.10" || \
+                  "$GKIVERSION" == "android13-5.15" ]]; then
+
+              # Detect Conflicting Swap Slots Include
+              if grep -qxF '#include <linux/swap_slots.h>' ./mm/memory.c && \
+                 ! grep -qxF '#include <linux/susfs_def.h>' ./mm/memory.c; then
+
+                echo "🔧 Detected Interfering Swap Slots Include, Temporarily Removing"
+
                 FAKEPATCHED=1
               fi
-            fi  
+
+              # Check for Missing VMA Pages Fix
+              if ! grep -qxF $'\tif (!vma_pages(vma))' ./fs/proc/task_mmu.c; then
+                echo "🛠️ Missing VMA Pages Fix"
+
+                FAKEPATCHED=1
+              fi
+            fi
 
             # SUSFS Core Patch (50 Add SUSFS Patch)
             echo "⚙️ Applying SUSFS Core Patch (50 Add SUSFS Patch)"
