Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -312,10 +312,6 @@ jobs:
       # Performance + Reuse
       CCACHE_SLOPPINESS: file_macro,time_macros,include_file_mtime,include_file_ctime
 
-      # Compression Tuning
-      CCACHE_COMPRESS: "true"
-      CCACHE_COMPRESSLEVEL: "6"
-
       # Kernel-Specific Optimization
       CCACHE_IS_KERNEL_COMPILING: "true"
 
@@ -4573,14 +4569,14 @@ jobs:
           export CCACHE_BASEDIR="${{ env.CCACHE_BASEDIR }}" || echo "⚠️ Base Directory Not Found"
           export CCACHE_NOHASHDIR="${{ env.CCACHE_NOHASHDIR }}" || echo "⚠️ NoHash Directory Not Found"
           export CCACHE_NOHARDLINK="${{ env.CCACHE_NOHARDLINK }}" || echo "⚠️ Cache Hardlink Not Found"    
-                   
+          export CCACHE_IS_KERNEL_COMPILING="${{ env.CCACHE_IS_KERNEL_COMPILING }}" || echo "⚠️ Cache Is Kernel Compiling Not Found"    
+                            
           # Force Optimal Runtime Behavior
           ccache -F 0
           ccache -o direct_mode=true \
                  -o hash_dir=false \
                  -o depend_mode=true \
-                 -o compression=true \
-                 -o compression_level=6
+                 -o compression=true
 
           # Kernel Sloppiness
           CCACHECONF="${CCACHE_DIR}/ccache.conf"
