Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -2699,13 +2699,11 @@ jobs:
 
             # Apply Patch Using Git Apply
             if [[ "$PATCHNAME" == "001-lz4.patch" ]]; then
-              # Use Git Apply for LZ4 Patch
-              git apply --ignore-whitespace -p1 < "$PATCHFILE" || true
-              echo "🔧 LZ4 1.10.0 Patch Applied Successfully"
+              git apply --ignore-whitespace -p1 < "$PATCHFILE" || echo "⚠️ $PATCHNAME Failed, but Continuing..."
+              echo "✔️ $PATCHNAME Applied"
             else
-              # Use Patch for ZSTD Patch
-              patch --ignore-whitespace -p1 < "$PATCHFILE" || true
-              echo "🔧 ZSTD 1.5.7 Patch Applied Successfully"
+              patch --ignore-whitespace -p1 < "$PATCHFILE" || echo "⚠️ $PATCHNAME Failed, but Continuing..."
+              echo "✔️ $PATCHNAME Applied"
             fi
           }
 
