Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -2708,10 +2708,6 @@ jobs:
 
           echo "==== ZRAM Module Processing ===="
 
-          # Clean Old Module
-          rm -rf "$MODULE_DIR"
-          mkdir -p "$MODULE_DIR/zram"
-
           echo "🔎 Searching for ZRAM Template Zip..."
 
           ZRAM_ZIP=$(find "$GITHUB_WORKSPACE" -type f -name "ZRAM.zip" | head -n 1 || true)
@@ -2726,9 +2722,9 @@ jobs:
           echo "$ZRAM_ZIP"
 
           echo "📦 Extracting ZRAM Module Template"
-          unzip -q "$ZRAM_ZIP" -d "$MODULE_DIR"
+          unzip -o -q "$ZRAM_ZIP"
 
-          CONFIG_PROP="${MODULE_DIR}/config.prop"
+          CONFIG_PROP="config.prop"
 
           if [[ ! -f "$CONFIG_PROP" ]]; then
             echo "❌ Config.prop Missing Inside Template"
@@ -2737,29 +2733,31 @@ jobs:
           fi
 
           echo "⚙ Updating Config.prop"
-          sed -i "s/^ZRAM_ALGO=.*/ZRAM_ALGO=${ZRAM_ALGO}/" "$CONFIG_PROP"
-          sed -i "s/^ZRAM_SIZE=.*/ZRAM_SIZE=${ZRAM_SIZE}/" "$CONFIG_PROP"
+
+          sed -i "s/^ZRAM_ALGO=.*/ZRAM_ALGO=${ZRAM_ALGO}/" "$CONFIG_PROP" || true
+          sed -i "s/^ZRAM_SIZE=.*/ZRAM_SIZE=${ZRAM_SIZE}/" "$CONFIG_PROP" || true
 
           echo "Algorithm: ${ZRAM_ALGO}"
           echo "Size: ${ZRAM_SIZE}"
 
           echo "🔎 Searching for Compiled ZRAM.ko..."
 
-          zram_path=$(find kernel_workspace -type f -name "zram.ko" | head -n 1 || true)
+          zram_path=$(find "$GITHUB_WORKSPACE" -type f -name "zram.ko" | head -n 1 || true)
 
           if [[ -n "$zram_path" ]]; then
             echo "✅ ZRAM Module Found:"
             echo "$zram_path"
 
+            mkdir -p "${MODULE_DIR}/zram"
             install -D "$zram_path" "$TARGET"
 
             echo "upload=true" >> "$GITHUB_OUTPUT"
             echo "ZRAM Module Successfully Prepared"
           else
-            echo "❌ ZRAM.ko Not Found"
+            echo "❌ zram.ko Not Found"
 
             echo "Debug: Searching Possible ZRAM Files"
-            find kernel_workspace -name "*zram*" || true
+            find "$GITHUB_WORKSPACE" -name "*zram*" || true
 
             echo "upload=false" >> "$GITHUB_OUTPUT"
             exit 0
