Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -5046,30 +5046,31 @@ jobs:
           echo "💡 Creating Baseline Checksum..."
           sha256sum Image > Image.sha256
       
-          # Download Tools 
+          # Download KernelPatch-Next Tools 
           echo "📥 Downloading KernelPatch-Next Tools..."
       
-          download() {
-            local url="$1"
-            local out="$2"
-      
-            wget --tries=3 --timeout=20 -O "$out" "$url" || return 1
-            [[ -s "$out" ]] || return 1
-      
-            if file "$out" | grep -qi "html"; then
-              echo "⚠️ Invalid Download (HTML Detected): $out"
-              return 1
-            fi
-      
-            chmod +x "$out"
-          }
-      
-          download "https://github.com/KernelSU-Next/KPatch-Next/releases/latest/download/kptools-linux" kptools-linux \
-            || { echo "⚠️ Failed to Download KP-Tools"; exit 1; }
-      
-          download "https://github.com/KernelSU-Next/KPatch-Next/releases/latest/download/kpimg-linux" kpimg-linux \
-            || { echo "⚠️ Failed to Download KP-Img"; exit 1; }
-      
+          KPREPO="KernelSU-Next/KPatch-Next"
+          URLAPI="https://api.github.com/repos/$KPREPO/releases/latest"
+
+          URLKPTOOLS=$(curl -s "$URLAPI" | grep browser_download_url | grep -i "kptools" | cut -d '"' -f 4)
+          URLKPIMG=$(curl -s "$URLAPI" | grep browser_download_url | grep -i "kpimg" | cut -d '"' -f 4)
+
+          if [[ -z "$URLKPTOOLS" || -z "$URLKPIMG" ]]; then
+            echo "⚠️ Failed to Resolve KernelPatch-Next Assets..."
+            exit 1
+          fi
+
+          echo "------------------------------"
+          echo "📦 KernelPatch-Next KPTools : $URLKPTOOLS"
+          echo "📦 KernelPatch-Next KPImg   : $URLKPIMG"
+          echo "------------------------------"
+          echo ""
+
+          curl -L --retry 5 --fail -o kptools-linux "$URLKPTOOLS"
+          curl -L --retry 5 --fail -o kpimg-linux "$URLKPIMG"
+
+          chmod +x kptools-linux
+          
           # Apply patch
           echo "⚙️ Patching Kernel Image..."
       
@@ -5091,7 +5092,7 @@ jobs:
             echo "🧩 Image Modified by KernelPatch-Next (Expected)"
           fi
       
-          # Sync to AnyKernel3      
+          # Sync and Copy to AnyKernel3      
           [[ -d "$AK3DIRECTORY" ]] || { echo "⚠️ AnyKernel3 Not Found"; exit 1; }
       
           echo "📩 Copying to AnyKernel3..."
