Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -2263,16 +2263,15 @@ jobs:
 
               echo "⚙️ Applying SUSFS 69 Enable Hide Patch to $ROOTENGINE..."
 
-              if ! wget -q --show-error --retry-connrefused --tries=3 --timeout=15 \
-                "$PATCH69URL" -O "$PATCH69FILE"; then
-                echo "⚠️ Failed to Download Patch"
+              if ! wget -q "$PATCH69URL" -O "$PATCH69FILE"; then
+                echo "⚠️ Failed to Download SUSFS 69 Enable Hide Patch"
                 exit 1
               fi
 
               if patch -p1 -N -F 3 < "$PATCH69FILE"; then
                 echo "🔧 SUSFS 69 Enable Hide Patch Applied"
               else
-                echo "⚠️ Patch Not Applied (Already Applied or Failed)"
+                echo "⚠️ SUSFS 69 Enabled Hide Patch Not Applied (Already Applied or Failed)"
               fi
 
               rm -f "$PATCH69FILE"
