Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -4568,26 +4568,23 @@ jobs:
           CACHE_DIR="../cache"      
           savefastccache() {
             echo "📦 Saving Fast Build Cache..."
-
             # Ensure the Fallback Cache Directory Exists
-            mkdir -p "$CACHE_DIR"
+            mkdir -p "$CACHE_DIR" || {
+              echo "⚠️ Unable to Create Fast Build Cache"
+              return 0
+            }
 
             # Save the Kernel Configuration
-            if [[ -f out/.config ]]; then
-              cp -f out/.config "$CACHE_DIR/.config"
-            fi
-
+            [[ -f out/.config ]] &&
+              cp -f out/.config "$CACHE_DIR/.config" || true
             # Save Generated Kernel Headers
             if [[ -d out/include ]]; then
-              rm -rf "$CACHE_DIR/include"
-              cp -rf out/include "$CACHE_DIR/"
+              rm -rf "$CACHE_DIR/include" || true
+              cp -rf out/include "$CACHE_DIR/" || true
             fi
-
             # Save Module Symbol Information
-            if [[ -f out/Module.symvers ]]; then
-              cp -f out/Module.symvers "$CACHE_DIR/Module.symvers"
-            fi
-
+            [[ -f out/Module.symvers ]] &&
+              cp -f out/Module.symvers "$CACHE_DIR/Module.symvers" || true
             echo "✔️ Fast Build Cache Saved"
           }
 
