Update Matrix SM-8750.yml

diff --git a/.github/workflows/Matrix SM-8750.yml b/.github/workflows/Matrix SM-8750.yml
--- a/.github/workflows/Matrix SM-8750.yml
+++ b/.github/workflows/Matrix SM-8750.yml
@@ -2475,6 +2475,7 @@ jobs:
           fi
       
           cd "$COMMON_DIR"
+          
           echo "➡️  Working Directory: $(pwd)"
           echo "🔧 Enabling Kernel-Level Baseband Guard Support..."
       
@@ -2608,12 +2609,18 @@ jobs:
           # ------------------------------
           # Navigate to Kernel Common Directory
           # ------------------------------
-          KERNEL_COMMON_DIR="kernel_workspace/${{ matrix.FILE }}/kernel_platform/common"
-          if [ ! -d "$KERNEL_COMMON_DIR" ]; then
-            echo "⚠️ Kernel Common Directory Not Found, Skipping Patch Step"
-            exit 0
+          BASE="$GITHUB_WORKSPACE/kernel_workspace/${{ matrix.FILE }}"
+
+          if [[ -d "$BASE/kernel_platform/common" ]]; then
+            COMMON_DIR="$BASE/kernel_platform/common"
+          elif [[ -d "$BASE/common" ]]; then
+            COMMON_DIR="$BASE/common"
+          else
+            echo "⚠️ ERROR: Common Directory Not Found"
+            exit 1
           fi
-          cd "$KERNEL_COMMON_DIR"
+          
+          cd "$COMMON_DIR"
 
           # ------------------------------
           # Detect Kernel Version
@@ -2757,11 +2764,14 @@ jobs:
 
           if [[ -d "$BASE/kernel_platform/common" ]]; then
             COMMON_DIR="$BASE/kernel_platform/common"
-          else
+          elif [[ -d "$BASE/common" ]]; then
             COMMON_DIR="$BASE/common"
+          else
+            echo "⚠️ ERROR: Common Directory Not Found"
+            exit 1
           fi
 
-          cd "$GITHUB_WORKSPACE/kernel_workspace/${{ matrix.FILE }}"
+          cd "$COMMON_DIR"
           
           # ------------------------------
           # Set the Path to the Configuration File
@@ -3230,8 +3240,18 @@ jobs:
           echo "KBUILD_BUILD_TIMESTAMP=${DATESTR}" >> "$GITHUB_ENV"
           echo "KBUILD_BUILD_VERSION=1" >> "$GITHUB_ENV"
       
-          KERNEL_DIR="${GITHUB_WORKSPACE}/kernel_workspace/${{ matrix.FILE }}/kernel_platform"
-          cd "$KERNEL_DIR" || { echo "⚠️ Kernel Directory Not Found: $KERNEL_DIR"; exit 1; }
+          BASE="$GITHUB_WORKSPACE/kernel_workspace/${{ matrix.FILE }}"
+
+          if [[ -d "$BASE/kernel_platform/common" ]]; then
+            COMMON_DIR="$BASE/kernel_platform/common"
+          elif [[ -d "$BASE/common" ]]; then
+            COMMON_DIR="$BASE/common"
+          else
+            echo "⚠️ ERROR: Common Directory Not Found"
+            exit 1
+          fi
+          
+          cd "$COMMON_DIR" || { echo "⚠️ Kernel Directory Not Found: $KERNEL_DIR"; exit 1; }
       
           # ------------------------------
           # Patch MKCompile Scripts
@@ -3328,11 +3348,16 @@ jobs:
           KERNEL_VERSION="${{ env.KERNEL_VERSION }}"
           BASE="$GITHUB_WORKSPACE/kernel_workspace/${{ matrix.FILE }}"
 
-          if [[ -d "$BASE/kernel_platform" ]]; then
-            cd "$BASE/kernel_platform"
+          if [[ -d "$BASE/kernel_platform/common" ]]; then
+            COMMON_DIR="$BASE/kernel_platform/common"
+          elif [[ -d "$BASE/common" ]]; then
+            COMMON_DIR="$BASE/common"
           else
-            cd "$BASE"
+            echo "⚠️ ERROR: Common Directory Not Found"
+            exit 1
           fi
+
+          cd "$COMMON_DIR"
           
           # ------------------------------
           # Detect LLVM IAS
