Update Matrix SM-8750.yml

diff --git a/.github/workflows/Matrix SM-8750.yml b/.github/workflows/Matrix SM-8750.yml
--- a/.github/workflows/Matrix SM-8750.yml
+++ b/.github/workflows/Matrix SM-8750.yml
@@ -1380,7 +1380,7 @@ jobs:
               "https://raw.githubusercontent.com/${REPO}/${MANAGER_BRANCH}/kernel/setup.sh" \
               | bash -s "$MANAGER_BRANCH"
 
-            echo 'CONFIG_KSU_FULL_NAME_FORMAT="%TAG_NAME%"' >> ./common/arch/arm64/configs/gki_defconfig
+            echo 'CONFIG_KSU_FULL_NAME_FORMAT="%TAG_NAME%"' >> ./arch/arm64/configs/gki_defconfig
 
             cd ./KernelSU || exit 1
 
@@ -3206,21 +3206,23 @@ jobs:
           echo "------------------------------"
       
           PATCH_DIR="${GITHUB_WORKSPACE}/kernel_workspace/AndreiMikh-Kernel-Lab/patches"
-          TARGET_DIR="${GITHUB_WORKSPACE}/kernel_workspace/${{ matrix.FILE }}/kernel_platform/common"
+          
+          BASE="$GITHUB_WORKSPACE/kernel_workspace/${{ matrix.FILE }}"
+
+          if [[ -d "$BASE/kernel_platform/common" ]]; then
+            COMMON_DIR="$BASE/kernel_platform/common"
+          elif [[ -d "$BASE/common" ]]; then
+            COMMON_DIR="$BASE/common"
+          else
+            echo "⚠️ ERROR: Common Directory Not Found"
+            exit 1
+          fi
+          
           PATCH_FILE="${PATCH_DIR}/IPv6.patch"
       
           echo "✔️ NetFilter Enabled — 🔎 Checking IPv6 NAT Compatibility..."
       
-          # ------------------------------
-          # Validate Target Directory
-          # ------------------------------
-          if [[ ! -d "$TARGET_DIR" ]]; then
-              echo "⚠️ Target Directory Not Found:"
-              echo "$TARGET_DIR"
-              exit 1
-          fi
-      
-          cd "$TARGET_DIR"
+          cd "$COMMON_DIR"
       
           # ------------------------------
           # Validate Patch File
@@ -3274,7 +3276,7 @@ jobs:
           # ------------------------------
           INPUT_TIME="${{ github.event.inputs.BUILD_TIME }}"
       
-          if [[ -n "$INPUT_TIME" && "$INPUT_TIME" != [Ff] ]]; then
+          if [[ -n "$INPUT_TIME" && "$INPUT_TIME" != [Ff]$ ]]; then
               DATESTR="$INPUT_TIME"
               echo "🔎 Using Input Build Time: $DATESTR"
           else
