Update Matrix SM-8750.yml

diff --git a/.github/workflows/Matrix SM-8750.yml b/.github/workflows/Matrix SM-8750.yml
--- a/.github/workflows/Matrix SM-8750.yml
+++ b/.github/workflows/Matrix SM-8750.yml
@@ -1051,8 +1051,17 @@ jobs:
         if: ${{ github.event.inputs.SUFFIX != '' }}
         run: |
           BASE="$GITHUB_WORKSPACE/kernel_workspace/${{ matrix.FILE }}"
+
+          if [[ -d "$BASE/kernel_platform/common" ]]; then
+            COMMON_DIR="$BASE/kernel_platform/common"
+          elif [[ -d "$BASE/common" ]]; then
+            COMMON_DIR="$BASE/common"
+          else
+            echo "⚠️ ERROR: Common Directory Not Found"
+            exit 1
+          fi
           
-          cd "$BASE"
+          cd "$COMMON_DIR"
 
           SUFFIX="${{ github.event.inputs.SUFFIX }}"
           KANDROID_VERSION="${{ env.KANDROID_VERSION }}"
