Update Stable V9.3.yml

diff --git a/.github/workflows/Stable V9.3.yml b/.github/workflows/Stable V9.3.yml
--- a/.github/workflows/Stable V9.3.yml
+++ b/.github/workflows/Stable V9.3.yml
@@ -1781,6 +1781,24 @@ jobs:
               echo "🧹 Removing Patch: ($FILE)..."
               rm -f "$FILE"
             done
+
+            # Detect Default Configuration Path
+            if [[ -f ../common/arch/arm64/configs/gki_defconfig ]]; then
+              DEFCONFIG="../common/arch/arm64/configs/gki_defconfig"
+            elif [[ -f ../arch/arm64/configs/gki_defconfig ]]; then
+              DEFCONFIG="../arch/arm64/configs/gki_defconfig"
+            else
+              echo "⚠️ GKI Default Configuration Not Found!"
+              exit 1
+            fi     
+             
+            # Temporarily Disable Manual Hook if SUSFS is Enabled
+            if [[ "$SUSFS" != "-1" ]]; then
+              echo "CONFIG_KSU_KPROBES_HOOK=n" >> "$DEFCONFIG"
+              echo "✔️ Kprobes Hook Disabled"
+            else
+              echo "⚠️ Failed to Disable Kprobes Hook"
+            fi
       
             echo "🎉 KernelSU-Next Setup Complete"
       
