Update Stable V9.3.yml

diff --git a/.github/workflows/Stable V9.3.yml b/.github/workflows/Stable V9.3.yml
--- a/.github/workflows/Stable V9.3.yml
+++ b/.github/workflows/Stable V9.3.yml
@@ -1643,13 +1643,13 @@ jobs:
             # Download and Run Setup Script 
             curl -fsSL \
               "https://raw.githubusercontent.com/${REPO}/${MANAGER_BRANCH}/kernel/setup.sh" \
-              | bash -s builtin
+              | bash -s "$MANAGER_BRANCH"
               
             cd KernelSU || exit 1
       
             # Get Current Git Commit Short Commit Hash (8 Characters)
             GIT_COMMIT_HASH=$(git rev-parse --short=8 HEAD)
-            echo "Commit hash: $GIT_COMMIT_HASH"
+            echo "📃 Commit Hash: $GIT_COMMIT_HASH"
       
             # Fetch KSU API Version (Retry Up to 3 Times)
             for i in {1..3}; do
@@ -1692,16 +1692,16 @@ jobs:
       
             # Verify (Non-Fatal)
             echo "Checking Repo Owner Section..."
-            grep -A10 "REPO_OWNER" kernel/Makefile || echo "Repository Owner Not Found"
+            grep -A10 "REPO_OWNER" kernel/Makefile || echo "⚠️ ${ROOTENGINE} Repository Owner Not Found"
             
             echo "Checking KSU version..."
-            grep "KSU_VERSION_FULL" kernel/Makefile || echo "KSU Version Not Found"
+            grep "KSU_VERSION_FULL" kernel/Makefile || echo "⚠️ ${ROOTENGINE} Version Not Found"
         
-            echo "SukiSU Version: v${KSU_API_VERSION}-${GIT_COMMIT_HASH}@Andrei"
+            echo "SukiSU Version: v${KSU_API_VERSION}-${GIT_COMMIT_HASH}"
 
             # Clean Old Entry and Add New Format
             sed -i '/KSU_VERSION_FULL/d' "$DEFCONFIG"
-            printf 'KSU_VERSION_FULL="v$(VERSION_TAG)-$KSU_VERSION"\n' >> "$DEFCONFIG"         
+            printf 'KSU_VERSION_FULL="$VERSION_TAG-$KSU_VERSION-Andrei"\n' >> "$DEFCONFIG"         
              
             # Temporarily Disable Manual Hook if SUSFS is Enabled
             if [[ "$SUSFS" != "-1" ]]; then
