Update Stable V9.3.yml

diff --git a/.github/workflows/Stable V9.3.yml b/.github/workflows/Stable V9.3.yml
--- a/.github/workflows/Stable V9.3.yml
+++ b/.github/workflows/Stable V9.3.yml
@@ -1572,7 +1572,8 @@ jobs:
       
           MANAGER_BRANCH="${{ steps.manager.outputs.MANAGER_BRANCH }}"
           ROOTENGINE="${{ github.event.inputs.ROOTENGINE }}"
-      
+          SUSFS="${{ github.event.inputs.SUSFS }}"      
+          
           # Helper Functions      
           # Get Commit-Count-Based Version
           get_commit_count_version() {
@@ -1658,8 +1659,27 @@ jobs:
             
             echo "Checking KSU version..."
             grep "KSU_VERSION_FULL" kernel/Makefile || echo "KSU Version Not Found"
-      
+        
             echo "SukiSU Version: v${KSU_API_VERSION}-${GIT_COMMIT_HASH}@Andrei"
+          
+            # Detect Default Configuration Path
+            if [[ -f ../common/arch/arm64/configs/gki_defconfig ]]; then
+              DEFCONFIG="../common/arch/arm64/configs/gki_defconfig"
+            elif [[ -f ../arch/arm64/configs/gki_defconfig ]]; then
+              DEFCONFIG="../arch/arm64/configs/gki_defconfig"
+            else
+              echo "⚠️ GKI Default Configuration Not Found!"
+              exit 1
+            fi     
+             
+            # Temporarily Disable Manual Hook if SUSFS is Enabled
+            if [[ "$SUSFS" != "-1" ]]; then
+              echo "CONFIG_KSU_MANUAL_HOOK=n" >> "$DEFCONFIG"
+              echo "✔️ Manual Hook Disabled"
+            else
+              echo "⚠️ Failed to Disable Manual Hook"
+            fi
+            
             echo "🎉 SukiSU-Ultra Ready"
       
           # ReSukiSU Setup
@@ -2591,7 +2611,7 @@ jobs:
 
           # Kernel and Patch Directories
           KERNEL_DIR="${GITHUB_WORKSPACE}/kernel_workspace/kernel_platform/common"
-          CONFIG_FILE="${KERNEL_DIR}/arch/arm64/configs/gki_defconfig"
+          DEFCONFIG="${KERNEL_DIR}/arch/arm64/configs/gki_defconfig"
       
           BASE_PATCH_DIR="${GITHUB_WORKSPACE}/kernel_workspace/SukiSU_patch/other/zram/zram_patch"
           PATCH_DIR=$(find "$BASE_PATCH_DIR" -maxdepth 1 -type d -name "${KERNELVERSION}*" | sort -V | tail -n 1 || true)
@@ -2643,7 +2663,7 @@ jobs:
               if [[ "$ZRAM_ALGO" != "lz4" ]]; then
 
                   # Non-LZ4 Base ZRAM Options
-                  cat >> "$CONFIG_FILE" << EOF
+                  cat >> "$DEFCONFIG" << EOF
           CONFIG_CRYPTO_LZ4HC=y
           CONFIG_CRYPTO_LZ4K=y
           CONFIG_CRYPTO_LZ4KD=y
@@ -2658,7 +2678,7 @@ jobs:
               else
 
                   # LZ4 ZRAM Options
-                  cat >> "$CONFIG_FILE" << EOF
+                  cat >> "$DEFCONFIG" << EOF
           CONFIG_ZSMALLOC=y
           CONFIG_CRYPTO_LZ4HC=y
           CONFIG_CRYPTO_LZ4K=y
