Update Stable V9.3.yml

diff --git a/.github/workflows/Stable V9.3.yml b/.github/workflows/Stable V9.3.yml
--- a/.github/workflows/Stable V9.3.yml
+++ b/.github/workflows/Stable V9.3.yml
@@ -234,6 +234,7 @@ on:
         default: Performance
         options:
           - Performance
+          - Experimental
           - Disable 
 
 jobs:
@@ -319,6 +320,11 @@ jobs:
             Performance)
               CLEANSPACE=Disabled
               BUILDCCACHE=Enabled
+              XUS=Enabled
+              ;;
+            Experimental)
+              CLEANSPACE=Disabled
+              BUILDCCACHE=Disabled
               XUS=Enabled
               ;;
             Disable)
@@ -850,9 +856,39 @@ jobs:
           git config --global --list
 
       # ==============================
-      # Restore Compiler Cache
+      # Restore Compiler Cache From GitHub Release
       # ==============================
-      - name: 🔧 Restore Compiler Cache
+      - name: 🔧 Restore Compiler Cache From GitHub Release
+        run: |
+          set -euo pipefail
+
+          # Define the Release Asset
+          TAR="CCache-${{ runner.os }}-${{ env.FILE_BASE }}-${{ github.ref_name }}.tar.gz"
+
+          # Build the Download URL
+          URL="https://github.com/AndreiMikh/CCache/releases/download/001/${TAR}"
+          echo "Downloading from: $URL"
+
+          # Ensure Cache Directory Exists
+          mkdir -p "$CCACHE_DIR"
+
+          # Download
+          curl -fsSL -o "$TAR_NAME" "$DOWNLOAD_URL" || {
+            echo "⚠️ Release Cache Not Found, Continuing Without Restoring from Release..."
+            exit 0
+          }
+
+          # Extract into Cache
+          echo "📩 Extracting $TAR to $CCACHEDIR..."
+          tar -xzf "$TAR" -C "$CCACHEDIR"
+
+          # List contents for debugging
+          ls -la "$CCACHEDIR"
+
+      # ==============================
+      # Restore Compiler Cache (Local)
+      # ==============================
+      - name: 🔧 Restore Compiler Cache (Local)
         id: restore-cache 
         if: ${{ env.BUILDCCACHE != 'Disabled' }}
         uses: actions/cache@v5
