Update Stable V9.4.yml

diff --git a/.github/workflows/Stable V9.4.yml b/.github/workflows/Stable V9.4.yml
--- a/.github/workflows/Stable V9.4.yml
+++ b/.github/workflows/Stable V9.4.yml
@@ -2121,44 +2121,36 @@ jobs:
       
           cd ..
       
-          # Find SUSFS Patch
-          echo "🔎 Searching SUSFS Patch..."
+          # Find SUSFS Patches
+          echo "🔎 Searching SUSFS Patches..."
       
           shopt -s nullglob
-          PATCH_LIST=(./susfs4ksu/kernel_patches/50_add_susfs_in_gki-${ANDROIDVERSION}-${KERNELVERSION}*.patch)
+          SUSFSPATCHLIST=(./susfs4ksu/kernel_patches/50_add_susfs_in_gki-${ANDROIDVERSION}-${KERNELVERSION}*.patch)
       
-          if [[ ${#PATCH_LIST[@]} -eq 0 ]]; then
+          if [[ ${#SUSFSPATCHLIST[@]} -eq 0 ]]; then
             echo "⚠️ No SUSFS Patch Found"
             ls ./susfs4ksu/kernel_patches/ || true
             exit 1
           fi
       
-          SUS_PATCH="${PATCH_LIST[-1]}"
+          SUSFSPATCH="${SUSFSPATCHLIST[-1]}"
       
-          echo "🧾 Using Patch: $SUS_PATCH"
+          echo "🧾 Using Patch: $SUSFSPATCH"
       
-          cp "$SUS_PATCH" "$KDIR/"
+          cp "$SUSFSPATCH" "$KDIR/"
           cp -r ./susfs4ksu/kernel_patches/fs/* "$KDIR/fs/" || true
           cp -r ./susfs4ksu/kernel_patches/include/linux/* "$KDIR/include/linux/" || true
       
           cd "$KDIR"
       
-          # Apply SUSFS Core Patch
-          echo "⚙️ Applying SUSFS Core Patch..."
-          patch -p1 < "$(basename "$SUS_PATCH")" || true
+          # Apply SUSFS Core Patch (50 Add SUSFS Patch)
+          echo "⚙️ Applying SUSFS Core Patch (50 Add SUSFS Patch)"
+          patch -p1 < "$(basename "$SUSFSPATCH")" || true
       
-          # SUSFS Hide Patch
-          if [[ "$GKIVERSION" == *"6.1"* || "$GKIVERSION" == *"6.6"* || "$ROOTENGINE" == "SukiSU-Ultra" || "$ROOTENGINE" == "ReSukiSU" ]]; then
-            echo "⚙️ Applying SUSFS Hide Patch..."
-            wget -q https://raw.githubusercontent.com/AndreiMikh/AndreiMikh-Kernel-Lab/LiquidAndrei/patches/69_hide_stuff.patch -O hide.patch
-            patch -p1 < hide.patch || true
-            rm -f hide.patch
-          fi
+          # SUSFS 10 Enable Patch for KernelSU
+          if [[ "$ROOTENGINE" == "KernelSU" ]]; then
       
-          # SUSFS Enable Patch
-          if [[ "$ROOTENGINE" == "KernelSU" || "$ROOTENGINE" == "KernelSU-Next" ]]; then
-      
-            echo "⚙️ SUSFS Enable Patch..."
+            echo "⚙️ SUSFS 10 Enable Patch..."
       
             URL="https://gitlab.com/simonpunk/susfs4ksu/-/raw/${BRANCH}/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch"
       
@@ -2459,8 +2451,7 @@ jobs:
           fi
                     
           # TrustyOS Missing Fix (6.6.0–6.6.30)
-          if [[ "${{ env.KV2 }}" == "66" && "${{ env.KV3 }}" -le 6630 && "$SUSFSREPOSITORY" != "-1" ]]; then
-          
+          if [[ "${{ env.KV2 }}" == "66" && "${{ env.KV3 }}" -le 6630 && "$SUSFSREPOSITORY" != "-1" ]]; then          
             TRUSTY_EXISTS=false
           
             if grep -q 'common-modules/trusty' "$GITHUB_WORKSPACE/.repo/manifests_fallback/${FILE}.xml"; then
@@ -2472,7 +2463,7 @@ jobs:
             if [[ "$TRUSTY_EXISTS" == false ]]; then
               echo "🛠️ Fixing Missing TrustyOS (Kernel 6.6.0–6.6.30)"
           
-              PATCHNAME=$(basename "$SUS_PATCH")
+              PATCHNAME=$(basename "$SUSFSPATCH")
           
               sed -i 's/-32,12 +32,38/-32,11 +32,37/g' "$PATCHNAME"
               sed -i '/#include <trace\/hooks\/fs.h>/d' "$PATCHNAME"
@@ -2480,49 +2471,40 @@ jobs:
           fi
                     
           # SUSFS Meta Fake Patch Workaround
-          if [[ "$SUSFSREPOSITORY" != "-1" ]]; then
-          
-            fake_patched=0
-          
+          if [[ "$SUSFSREPOSITORY" != "-1" ]]; then          
+            fake_patched=0          
             # Android 15 Kernel 6.6 Fix
-            if [[ "$GKIVERSION" == "android15-6.6" ]]; then
-          
+            if [[ "$GKIVERSION" == "android15-6.6" ]]; then          
               if ! grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' ./fs/proc/task_mmu.c; then
-                echo "⚠️ Missing NR Subpages Fix 🛠️ Applying Temporary Patch"
-          
+                echo "⚠️ Missing NR Subpages Fix 🛠️ Applying Temporary Patch"          
                 sed -i \
                   -e '/int ret = 0, copied = 0;/a \\tunsigned int nr_subpages \= __PAGE_SIZE \/ PAGE_SIZE;' \
                   -e '/int ret = 0, copied = 0;/a \\tpagemap_entry_t \*res = NULL;' \
-                  ./fs/proc/task_mmu.c
-          
+                  ./fs/proc/task_mmu.c          
                 fake_patched=1
               fi
           
               if ! grep -qxF '#include <linux/dma-buf.h>' ./fs/proc/base.c; then
-                echo "📩 Adding Missing DMA-BUF Header"
-          
+                echo "📩 Adding Missing DMA-BUF Header"          
                 sed -i '/#include <linux\/cpufreq_times.h>/a #include <linux\/dma-buf.h>' ./fs/proc/base.c
               fi
             fi
                     
             # Android 14 Kernel 6.1 Fix
-            if [[ "$GKIVERSION" == "android14-6.1" ]]; then
-          
+            if [[ "$GKIVERSION" == "android14-6.1" ]]; then          
               if ! grep -qxF $'\tif (!vma_pages(vma))' ./fs/proc/task_mmu.c; then
                 echo "🛠️ Missing VMA Pages Fix"
                 fake_patched=1
               fi
           
               if ! grep -qxF '#include <linux/dma-buf.h>' ./fs/proc/base.c; then
-                echo "📩 Adding DMA-BUF Header"
-          
+                echo "📩 Adding DMA-BUF Header"          
                 sed -i '/#include <linux\/cpufreq_times.h>/a #include <linux\/dma-buf.h>' ./fs/proc/base.c
               fi
             fi          
           
             # Android 12 / 13 Fix
-            if [[ "$GKIVERSION" == "android12-5.10" || "$GKIVERSION" == "android13-5.15" ]]; then
-          
+            if [[ "$GKIVERSION" == "android12-5.10" || "$GKIVERSION" == "android13-5.15" ]]; then          
               if ! grep -qxF $'\tif (!vma_pages(vma))' ./fs/proc/task_mmu.c; then
                 echo "🛠️ Missing VMA Pages Fix"
                 fake_patched=1
@@ -2530,12 +2512,9 @@ jobs:
             fi          
           
             # Revert Temporary Fake Patch
-            if [[ "$fake_patched" == 1 ]]; then
-          
-              echo "♻️ Reverting Temporary Fake Patch"
-          
-              if [[ "$GKIVERSION" == "android15-6.6" ]]; then
-          
+            if [[ "$fake_patched" == 1 ]]; then          
+              echo "♻️ Reverting Temporary Fake Patch"          
+              if [[ "$GKIVERSION" == "android15-6.6" ]]; then          
                 if grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' ./fs/proc/task_mmu.c; then
                   sed -i \
                     -e '/unsigned int nr_subpages \= __PAGE_SIZE \/ PAGE_SIZE;/d' \
@@ -2546,8 +2525,7 @@ jobs:
           
               if [[ "$GKIVERSION" == "android12-5.10" || \
                     "$GKIVERSION" == "android13-5.15" || \
-                    "$GKIVERSION" == "android14-6.1" ]]; then
-          
+                    "$GKIVERSION" == "android14-6.1" ]]; then          
                 if grep -qxF $'\t\t\tgoto show_pad;' ./fs/proc/task_mmu.c; then
                   sed -i 's/goto show_pad;/return 0;/' ./fs/proc/task_mmu.c
                 fi
@@ -2555,20 +2533,16 @@ jobs:
             fi
                     
             # Optional XUS Fix
-            if [[ "$XUS" == "Enabled" ]]; then
-          
-              echo "🛠️ Applying XUS Fix Patch"
-          
+            if [[ "$XUS" == "Enabled" ]]; then          
+              echo "🛠️ Applying XUS Fix Patch"          
               cp "$GITHUB_WORKSPACE/kernel_workspace/AndreiMikh-Kernel-Lab/patches/XUS-Fix.patch" ./
-              patch -p1 < XUS-Fix.patch || true
-          
+              patch -p1 < XUS-Fix.patch || true          
               echo "✔️ XUS Fix Patch Applied"
             fi
 
             # Primitive NTSynchronization (NTSync)
             if [[ "$NTSYNC" == "true" ]]; then
               echo "🛠️ Applying NTSync Patch..."
-
               if [[ -z "$GKIVERSION" ]]; then
                 echo "💢 Kernel Base Not Set — Provide a Valid Version!"
                 exit 1
