Update Test.yml

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -1483,6 +1483,8 @@ jobs:
 
             # Apply Fake Patch for Specific Android Versions
             if [ "$GKI_V" = "android15-6.6" ]; then
+            
+              # Add Fix for Page Map
               if ! grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' ./fs/proc/task_mmu.c; then
                 echo "NR Subpages Not Found, Apply Temporary Fix"
 
@@ -1494,10 +1496,18 @@ jobs:
                 fake_patched=1
               fi
 
+              # Add Fix for DMA-BUF
               if ! grep -qxF '#include <linux/dma-buf.h>' ./fs/proc/base.c; then
                 echo "Missing #include <linux/dma-buf.h>, Adding Header"
 
                 sed -i '/#include <linux\/cpufreq_times.h>/a #include <linux\/dma-buf.h>' ./fs/proc/base.c
+              fi
+
+              # Add Fix for SUSFS for KSU Patch
+              if ! grep -qxF '#include <linux/susfs.h>' ./fs/proc/base.c; then
+                echo "Missing SUSFS Header, Adding a Fix..."
+
+                sed -i '/#include <linux\/dma-buf.h>/a #include <linux\/susfs.h>' ./fs/proc/base.c
               fi
             fi
 
