Update Test.yml

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -5114,19 +5114,22 @@ jobs:
               | cut -d '"' -f 4)
           fi
          
-          # Final Check
+          # Final Fallback Check
           if [[ -z "$TAG" || "$TAG" == "null" ]]; then
-            echo "⚠️ Failed to Resolve KernelPatch-Next Tag"
-            exit 1
+            echo "⚠️ Failed to Resolve Tag → Using Fallback Tag Version"
+            TAG="0.13.5-2"
           fi
 
-          echo "🏷️ Latest Tag Detected: $TAG"
+          echo "🏷️ Using Tag : $TAG"
 
           # Build Download URLs from Tag
           BASE="https://github.com/$KPREPO/releases/download/$TAG"
 
           URLKPTOOLS="$BASE/kptools-linux"
           URLKPIMG="$BASE/kpimg-linux"
+
+          FALLKPTOOLS="https://raw.githubusercontent.com/AndreiMikh/AndreiMikh-Kernel-Lab/LiquidAndrei/patches/kptools-linux"
+          FALLKPIMG="https://raw.githubusercontent.com/AndreiMikh/AndreiMikh-Kernel-Lab/LiquidAndrei/patches/kpimg-linux"
 
           echo "------------------------------"
           echo "📦 KernelPatch-Next Latest Tag : $TAG"
@@ -5135,11 +5138,39 @@ jobs:
           echo "------------------------------"          
           echo ""
 
-          # Download
-          curl -L --retry 5 --fail -o kptools-linux "$URLKPTOOLS"
-          curl -L --retry 5 --fail -o kpimg-linux "$URLKPIMG"
+          # Download with Fallback
+          download() {
+            local primary="$1"
+            local fallback="$2"
+            local output="$3"
 
-          chmod +x kptools-linux
+            echo "📥 Downloading $output..."
+
+            curl -L \
+              -H "User-Agent: Mozilla/5.0" \
+              --fail \
+              --retry 5 \
+              --retry-all-errors \
+              --retry-delay 3 \
+              -o "$output" "$primary" || {
+
+              echo "⚠️ Primary Failed → Switching to Fallback..."
+
+              curl -L \
+                -H "User-Agent: Mozilla/5.0" \
+                --fail \
+                --retry 5 \
+                --retry-all-errors \
+                --retry-delay 3 \
+                -o "$output" "$fallback"
+            }
+
+            chmod +x "$output"
+          }
+
+          # Download Tools
+          download "$URLKPTOOLS" "$FALLKPTOOLS" "kptools-linux"
+          download "$URLKPIMG" "$FALLKPIMG" "kpimg-linux"
           
           # Apply patch
           echo "⚙️ Patching Kernel Image..."
@@ -5162,7 +5193,7 @@ jobs:
             echo "🧩 Image Modified by KernelPatch-Next (Expected)"
           fi
       
-          # Sync and Copy to AnyKernel3      
+          # Copy and Sync to AnyKernel3      
           [[ -d "$AK3DIRECTORY" ]] || { echo "⚠️ AnyKernel3 Not Found"; exit 1; }
       
           echo "📩 Copying to AnyKernel3..."
