Update Test 4.3.0.yml

diff --git a/.github/workflows/Test 4.3.0.yml b/.github/workflows/Test 4.3.0.yml
--- a/.github/workflows/Test 4.3.0.yml
+++ b/.github/workflows/Test 4.3.0.yml
@@ -3650,8 +3650,16 @@ jobs:
           echo "🚀 Applying KP-Next and Patching Kernel..."
           echo "------------------------------"
 
-          OUT_DIR="${GITHUB_WORKSPACE}/kernel_workspace/common/out/arch/arm64/boot"
+          OUT_DIR="${GITHUB_WORKSPACE}/kernel_workspace/kernel_platform/out/Final-Image-Find"
 
+          # ------------------------------
+          # Check Directory
+          # ------------------------------
+          if [[ ! -d "$OUT_DIR" ]]; then
+            echo "⚠️ Output Directory Not Found: $OUT_DIR"
+            exit 1
+          fi
+          
           # ------------------------------
           # Enter Kernel Output Directory
           # ------------------------------
@@ -3673,6 +3681,11 @@ jobs:
           # Apply Patch
           # ------------------------------
           echo "🛠️ Patching Kernel Image..."
+          if [[ ! -f Image ]]; then
+            echo "⚠️ Image Not Found"
+            exit 1
+          fi
+          
           ./kptools-linux -p -i Image -k kpimg-linux -o oImage
 
           # ------------------------------
