Update Test Optimizations.yml

diff --git a/.github/workflows/Test Optimizations.yml b/.github/workflows/Test Optimizations.yml
--- a/.github/workflows/Test Optimizations.yml
+++ b/.github/workflows/Test Optimizations.yml
@@ -3459,7 +3459,7 @@ jobs:
               ./common/build.config.common \
               ./"$KERNEL_REPOS"/build.config.common 2>/dev/null \
             | cut -d'=' -f2 \
-            | head -n1
+            | head -n1 || true
           )}"
 
           if [[ -z "$CLANG_PREBUILT_BIN" ]]; then
@@ -3577,27 +3577,32 @@ jobs:
 
           # Link Time Optimization (LTO) Configuration
           echo ">> 🧾 Configuring Link Time Optimization for Kernel $KERNEL_VERSION"
-          case "$KERNEL_VERSION" in
-            "5.10"|"5.15")
-              echo ">> 🚀 Link Time Optimization: Thin"
-              scripts/config --file out/.config \
-                -e LTO_CLANG \
-                -e LTO_CLANG_THIN \
-                -d LTO_CLANG_NONE \
-                -d LTO_CLANG_FULL
-              ;;
-            "6.12")
-              echo ">> 🚀 Link Time Optimization: None"
-              scripts/config --file out/.config \
-                -e LTO_CLANG \
-                -e LTO_CLANG_NONE \
-                -d LTO_CLANG_THIN \
-                -d LTO_CLANG_FULL
-              ;;
-            *)
-              echo ">> ⚠️ Link Time Optimization: Skipped for Kernel $KERNEL_VERSION"
-              ;;
-          esac
+
+          if [[ -f out/.config ]]; then
+            case "$KERNEL_VERSION" in
+              "5.10"|"5.15")
+                echo ">> 🚀 Link Time Optimization: Thin"
+                scripts/config --file out/.config \
+                  -e LTO_CLANG \
+                  -e LTO_CLANG_THIN \
+                  -d LTO_CLANG_NONE \
+                  -d LTO_CLANG_FULL
+                ;;
+              "6.12")
+                echo ">> 🚀 Link Time Optimization: None"
+                scripts/config --file out/.config \
+                  -e LTO_CLANG \
+                  -e LTO_CLANG_NONE \
+                  -d LTO_CLANG_THIN \
+                  -d LTO_CLANG_FULL
+                ;;
+              *)
+                echo ">> ⚠️ Link Time Optimization: Skipped for Kernel $KERNEL_VERSION"
+                ;;
+            esac
+          else
+            echo "⚠️ Configuration Not Found, Skipping LTO Configuration"
+          fi
 
           # Final Default Configuration and Build
           echo ">> 🚀 Running Old Default Configuration"
