Update Test - Stack Protector.yml

diff --git a/.github/workflows/Test - Stack Protector.yml b/.github/workflows/Test - Stack Protector.yml
--- a/.github/workflows/Test - Stack Protector.yml
+++ b/.github/workflows/Test - Stack Protector.yml
@@ -1524,7 +1524,14 @@ jobs:
           # ------------------------------
           # Enter Kernel Platform Directory
           # ------------------------------
-          cd kernel_platform
+          if [ -d "$CURRENT_DIR/kernel_platform" ]; then
+              cd "$CURRENT_DIR/kernel_platform"
+          elif [ -d "$CURRENT_DIR/kernel_workspace/kernel_platform" ]; then
+              cd "$CURRENT_DIR/kernel_workspace/kernel_platform"
+          else
+              echo "❌ ERROR: Kernel Platform Directory Not Found"
+              exit 1
+          fi
           
           # ------------------------------
           # Apply SukiSU ZRAM Patch
@@ -1690,8 +1697,8 @@ jobs:
           
           SUBLEVEL=$(grep '^SUBLEVEL *=' Makefile | head -n1 | cut -d= -f2 | tr -d ' ')
           
-          echo "📌 Kernel Base : $GKI_V"
-          echo "📌 Sublevel    : $SUBLEVEL"
+          echo "📌 Kernel Base   : $GKI_V"
+          echo "📌 Sublevel      : $SUBLEVEL"
           
           # ==============================
           # 5.15 Legacy C Library Compatibility Fix
