Update Test ABI Auto-Detect.yml

diff --git a/.github/workflows/Test ABI Auto-Detect.yml b/.github/workflows/Test ABI Auto-Detect.yml
--- a/.github/workflows/Test ABI Auto-Detect.yml
+++ b/.github/workflows/Test ABI Auto-Detect.yml
@@ -3101,9 +3101,12 @@ jobs:
           URL="https://raw.githubusercontent.com/WildKernels/kernel_patches/main/common/droidspaces/$PATCHNAME"
           PFILE="$GITHUB_WORKSPACE/$PATCHNAME"
           
-          echo "📩 Downloading Patch: $PATCHNAME"
-          
-          curl -fsSL "$URL" -o "$PFILE"
+          echo "📩 Downloading Patch From: $URL"          
+          curl -fsSL "$URL" -o "$PFILE" || {
+            echo "⚠️ Failed to Download Patch; Skipping..."
+          }
+
+          echo "
           
           if [[ ! -s "$PFILE" ]]; then
             echo "⚠️ Patch Download Failed or Empty..."
