Update Test.yml

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -1324,32 +1324,33 @@ jobs:
           # ==============================
           # Apply KernelSU / KernelSU-Next 10 Enable SUSFS Patch
           # ==============================
-          if [[ "${{ github.event.inputs.KSU_META }}" == "KernelSU" ]]; then          
-              echo "KernelSU Type Detected, Preparing SUSFS Enable Patch..."
+          KSU_META="${{ github.event.inputs.KSU_META }}"
+
+          if [[ "$KSU_META" == "KernelSU" || "$KSU_META" == "KernelSU-Next" ]]; then
+            echo "Applying 10 Enable SUSFS Patches for $KSU_META on $GKI_V"
+            if [[ "${{ github.event.inputs.SUSFS_VERSION }}" == "OGKI" ]]; then
+              PATCH_URL="https://raw.githubusercontent.com/cctv18/susfs4oki/oki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch"
+            else
+              PATCH_URL="https://gitlab.com/simonpunk/susfs4ksu/-/raw/gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch"
+            fi
           
-              if [[ "${{ github.event.inputs.SUSFS_VERSION }}" == "OGKI" ]]; then
-                  PATCH_URL="https://raw.githubusercontent.com/cctv18/susfs4oki/oki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch"
-              else
-                  PATCH_URL="https://gitlab.com/simonpunk/susfs4ksu/-/raw/gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch"
-              fi
+            echo "Downloading from: $PATCH_URL"
           
-              echo "Downloading from: $PATCH_URL"
+            wget -q "$PATCH_URL" -O enable_susfs.patch || true
           
-              wget -q "$PATCH_URL" -O enable_susfs.patch || true
+            if [[ -f "enable_susfs.patch" ]]; then
+              echo "Applying Patch Inside $KDIR"
           
-              if [[ -f "enable_susfs.patch" ]]; then
-                  echo "Applying Patch Inside $KDIR"
+              patch -d "$KDIR" -p1 --forward < enable_susfs.patch || true
           
-                  patch -d "$KDIR" -p1 --forward < enable_susfs.patch || true
+              rm -f enable_susfs.patch
           
-                  rm -f enable_susfs.patch
-          
-                  echo "✅ 10 Enable SUSFS Patch Applied!"
-              else
-                  echo "⚠️ Patch Not Found, Skipping"
-              fi
+              echo "✅ 10 Enable SUSFS Patch Applied!"
+            else
+              echo "⚠️ Patch Not Found, Skipping"
+            fi
           else
-              echo "❌ KernelSU or KernelSU-Next Not Selected, Skipping SUSFS 10 Enable Patch"
+            echo "❌ KernelSU or KernelSU-Next Not Selected, Skipping SUSFS 10 Enable Patch"
           fi
 
           cd - >/dev/null
