Update Test NTSync.yml

diff --git a/.github/workflows/Test NTSync.yml b/.github/workflows/Test NTSync.yml
--- a/.github/workflows/Test NTSync.yml
+++ b/.github/workflows/Test NTSync.yml
@@ -3209,11 +3209,25 @@ jobs:
           echo "🔎 Detected Kernel Base: $GKIVERSION"
           echo
 
-          # Directly Set Kernel Common Directory
-          KDIR="./kernel_patches/common"
+          # Detect Kernel Common Directory
+          if [[ -d "./kernel_platform/common" ]]; then
+            KDIR="./kernel_platform/common"
+          elif [[ -d "./common" ]]; then
+            KDIR="./common"
+          else
+            echo "⚠️ ERROR: Kernel Common Directory Not Found!"
+            exit 1
+          fi
 
           echo "📁 Kernel Directory: $KDIR"
           echo ""
+
+          # Check if the NTSync Directory Exists, and Create it if Missing
+          if [ ! -d "$KDIR/ntsync" ]; then
+            echo "⚠️ NTSync Directory Not Found... Creating the Directory..."
+            mkdir -p "$KDIR/ntsync"  # Create the directory
+            echo "📂 NTSync Directory Created"
+          fi
 
           # Navigate to the NTSYNC Patch Directory
           cd $KDIR/ntsync
