Update Test Optimizations.yml

diff --git a/.github/workflows/Test Optimizations.yml b/.github/workflows/Test Optimizations.yml
--- a/.github/workflows/Test Optimizations.yml
+++ b/.github/workflows/Test Optimizations.yml
@@ -3528,15 +3528,19 @@ jobs:
           export CCACHE_COMPRESS=true
           export CCACHE_COMPRESSLEVEL=6
           ccache -M 5G
-          ccache -s
-
+      
           if [[ "$ENABLE_RUST" == "true" ]]; then
             export BINDGEN="bindgen"
             export LIBCLANG_PATH="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/$(dirname "$CLANG_PREBUILT_BIN")/lib"
           fi
 
           # Enter Kernel Source Directory
-          cd ./common
+          if [[ -f ./common/Makefile ]]; then
+            cd ./common
+          else
+            echo "⚠️ Common Directory Not Found!"
+            exit 1
+          fi
 
           # Physical Path Remapping
           ROOT_REAL_PATH=$(realpath ../..)
