Update Test NTSync.yml

diff --git a/.github/workflows/Test NTSync.yml b/.github/workflows/Test NTSync.yml
--- a/.github/workflows/Test NTSync.yml
+++ b/.github/workflows/Test NTSync.yml
@@ -2307,17 +2307,25 @@ jobs:
 
               # Apply NTSync Compat Patch
               echo "➡️ Forwarding Patch for Kernel: ${KERNELVERSION}"
-              patch -p1 --forward < ntsync_compat_${GKIVERSION}.patch || {
+              patch -p1 < ntsync_compat_${GKIVERSION}.patch || {
                 echo "⚠️ Failed to Apply NTSync Compat Patch"
                 exit 1
               }
 
+              # Cleanup Compat Patch After Application
+              echo "🧹 Deleting NTSync Compat Patch"
+              rm -f ntsync_compat_${GKIVERSION}.patch
+
               # Apply NTSync Base Patch
               echo "➡️ Forwarding Patch for Kernel: ${KERNELVERSION}"
-              patch -p1 --forward < ntsync_base.patch || {
+              patch -p1 < ntsync_base.patch || {
                 echo "⚠️ Failed to Apply NTSync Base Patch"
                 exit 1
               }
+
+              # Cleanup Base Patch After Application
+              echo "🧹 Deleting NTSync Base Patch"
+              rm -f ntsync_base.patch
 
               # Success Message Indicating the Patches have been Applied Correctly
               echo "✔️ NTSync Patch Applied Successfully"
