Update Test.yml

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -4508,6 +4508,42 @@ jobs:
           echo "📦 Wrapper : $CCACHEWRAPPER"
           echo "📦 Clang   : $REALCLANGBIN"
 
+          # Configure ThinLTO Linker Cache for Supported 5.x Kernels
+          LDLLDWRAPPER=""
+          if [[ "${BUILDCCACHE:-Disabled}" != "Disabled" ]] && \
+             [[ "$KERNELVER" == 5.* ]]; then
+            LDCACHEDIR="$GITHUB_WORKSPACE/kernel_workspace/.thinlto-cache"
+            LDLLDWRAPPER="$GITHUB_WORKSPACE/kernel_workspace/ld-wrapper"
+
+            # Create ThinLTO Cache Directory
+            mkdir -p "$LDCACHEDIR"
+
+            # Locate LLVM LLD
+            LLDBIN="$(command -v ld.lld 2>/dev/null || true)"
+            if [[ -z "$LLDBIN" ]]; then
+              echo "⚠️ LD.LLD Not Found"
+              echo "📊 ThinLTO Linker Cache: Disabled"
+
+              LDLLDWRAPPER=""
+            else
+              # Create ThinLTO LLD Wrapper
+              printf '#!/bin/bash\nexec "%s" "$@" --thinlto-cache-dir="%s" --thinlto-cache-policy=cache_size_bytes=2g --thinlto-jobs=%s\n' \
+                "$LLDBIN" \
+                "$LDCACHEDIR" \
+                "$(nproc --all)" > "$LDLLDWRAPPER"
+              chmod +x "$LDLLDWRAPPER"
+
+              echo "🎉 ThinLTO Linker Wrapper Created"
+              echo "📦 Wrapper : $LDLLDWRAPPER"
+              echo "📦 LLD     : $LLDBIN"
+              echo "📂 Cache   : $LDCACHEDIR"
+              echo "💾 Cache   : 2 Gb"
+              echo "⚙️ Jobs    : $(nproc --all)"
+            fi
+          else
+            echo "📊 ThinLTO Linker Cache: Disabled"
+          fi
+
           # Prepare Kernel Based Arguments Shared by Build Configurations
           MAKE_ARGS=(
             LLVM=1
@@ -4515,7 +4551,7 @@ jobs:
             CROSS_COMPILE=aarch64-linux-gnu-
             CC="$CCACHEWRAPPER"
             HOSTCC="$CCACHEWRAPPER"
-            HOSTLD=ld.lld
+            HOSTLD="{LDLLDWRAPPER:-ld.lld}"
             PAHOLE="$PAHOLEBIN"
             KCFLAGS="${KCFLAGS[*]}"
             KCPPFLAGS="$KCPPFLAGS"
