Update Test.yml

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -1549,10 +1549,10 @@ jobs:
           echo "🧾 Reading Real Kernel Version..."
       
           VERSION=$(awk '/^VERSION =/ {print $3}' "$COMMONMAKEFILE")
-          PLVL=$(awk '/^PLVL =/ {print $3}' "$COMMONMAKEFILE")
-          SUBLVL=$(awk '/^SUBLVL =/ {print $3}' "$COMMONMAKEFILE")
+          PATCHLEVEL=$(awk '/^PATCHLEVEL =/ {print $3}' "$COMMONMAKEFILE")
+          SUBLEVEL=$(awk '/^SUBLEVEL =/ {print $3}' "$COMMONMAKEFILE")
       
-          OGVERSION="${VERSION}.${PLVL}.${SUBLVL}"
+          OGVERSION="${VERSION}.${PATCHLEVEL}.${SUBLEVEL}"
       
           echo "📌 Original Kernel Version: $OGVERSION"
           echo ""
@@ -1564,7 +1564,7 @@ jobs:
             echo "🛠️ Updating Kernel Sublevel..."
             echo "📌 New Sublevel: $SUBLVLINPUT"      
             sed -i \
-              "s/^\(SUBLVL[[:space:]]*=[[:space:]]*\).*/\1$SUBLVLINPUT/" \
+              "s/^\(SUBLEVEL[[:space:]]*=[[:space:]]*\).*/\1$SUBLVLINPUT/" \
               "$COMMONMAKEFILE"      
           else
             echo "📌 No Custom Sublevel Provided"
@@ -1575,8 +1575,8 @@ jobs:
           # Read Updated Kernel Version
           NEWVERSION=$(awk '
             /^VERSION =/ {v=$3}
-            /^PLVL =/ {p=$3}
-            /^SUBLVL =/ {s=$3}
+            /^PATCHLEVEL =/ {p=$3}
+            /^SUBLEVEL =/ {s=$3}
             END {print v "." p "." s}
           ' "$COMMONMAKEFILE")
       
@@ -2832,23 +2832,23 @@ jobs:
             echo "🎉 SUSFS Patches Complete"    
           
             # Extract Sublevel
-            SUBLVL=$(grep '^SUBLVL *=' Makefile | head -n1 | cut -d= -f2 | tr -d ' ')
+            SUBLEVEL=$(grep '^SUBLEVEL *=' Makefile | head -n1 | cut -d= -f2 | tr -d ' ')
           
             # Fallback if Empty
-            SUBLVL="${SUBLVL:-0}"
+            SUBLEVEL="${SUBLEVEL:-0}"
           
             # Validate Numeric
-            if ! [[ "$SUBLVL" =~ ^[0-9]+$ ]]; then
-              echo "⚠️ Invalid Sublevel Detected: $SUBLVL — forcing 0"
-              SUBLVL=0
+            if ! [[ "$SUBLEVEL" =~ ^[0-9]+$ ]]; then
+              echo "⚠️ Invalid Sublevel Detected: $SUBLEVEL — forcing 0"
+              SUBLEVEL=0
             fi
           
             echo "📂 Kernel Base   : $GKIVERSION"
-            echo "📂 Sublevel      : $SUBLVL"
+            echo "📂 Sublevel      : $SUBLEVEL"
             echo ""
           
             # 5.15 Legacy Fix
-            if [[ "$GKIVERSION" == "android13-5.15" && "$SUBLVL" -lt 123 ]]; then
+            if [[ "$GKIVERSION" == "android13-5.15" && "$SUBLEVEL" -lt 123 ]]; then
           
               LEGACYPATCH="$CURRENTDIR/AndreiMikh-Kernel-Lab/patches/Legacy-5.15-Fix.patch"
           
