Update Test Optimizations.yml

diff --git a/.github/workflows/Test Optimizations.yml b/.github/workflows/Test Optimizations.yml
--- a/.github/workflows/Test Optimizations.yml
+++ b/.github/workflows/Test Optimizations.yml
@@ -3603,7 +3603,7 @@ jobs:
 
           # Final Default Configuration and Build
           echo ">> 🚀 Running Old Default Configuration"
-          make O=out "${MAKE_ARGS[@]}" olddefconfig
+          make O=out "${MAKE_ARGS[@]}" olddefconfig || { echo "⚠️ Old Default Configuration Failed"; exit 1; }
           
           # System Resource Information
           echo "💻 CPU Threads: $(nproc)"
