Update Test 2.yml

diff --git a/.github/workflows/Test 2.yml b/.github/workflows/Test 2.yml
--- a/.github/workflows/Test 2.yml
+++ b/.github/workflows/Test 2.yml
@@ -312,6 +312,29 @@ jobs:
       - name: 🌿 Checkout LiquidAndrei
         uses: actions/checkout@v7
 
+      - name: 👤 Git Identity
+        shell: bash
+        run: |      
+          # Configure Git Identity if Not Already Set
+          if ! git config --global user.name >/dev/null; then
+            git config --global user.name "AndreiMikh"
+          fi
+          
+          if ! git config --global user.email >/dev/null; then
+            git config --global user.email "andreimikhail0088@gmail.com"
+          fi
+
+          # Clone Required Branch
+          echo "📥 Cloning Branch..."
+          git clone --depth=1 \
+            -b LiquidAndrei \
+            https://github.com/AndreiMikh/AndreiMikh-Kernel-Lab.git \
+            "$WORKDIR/AndreiMikh-Kernel-Lab"
+          echo "⚙️ Branch Cloned Successfully"
+          ls -la "$WORKDIR/AndreiMikh-Kernel-Lab"    
+          echo "🎉 Workspace Created and Git Configuration Applied:"
+          git config --global --list
+
       - name: 🚩 Build Profile Flags
         id: buildprofile
         shell: bash
@@ -382,6 +405,11 @@ jobs:
           # Workspace
           WORKSPACEDIR="${GITHUB_WORKSPACE}"
           WORKDIR="${WORKSPACEDIR}/kernel_workspace"
+          # Prepare the Workspace Directory
+          mkdir -p "$WORKDIR" || {
+            echo "⚠️ Failed to Create Directory: $WORKDIR"
+            exit 1
+          }
           # Kernel Lab
           LABDIR="${WORKDIR}/AndreiMikh-Kernel-Lab"
           # Kernel Platform
@@ -427,7 +455,6 @@ jobs:
           echo "Kernel Platform : ${KERNELPLATFORM}"
           echo "Common Kernel   : ${COMMONKERNELFOLDER}"
           echo "MSM Kernel      : ${MSMKERNELFOLDER}"
-          echo "Modules         : ${MODULESDIR}"
           echo "Patches         : ${PATCHDIR}"
           echo "Scripts         : ${SCRIPTSDIR}"
           echo "Libraries       : ${LIBDIR}"
@@ -445,35 +472,6 @@ jobs:
           remove-android: true          # Remove Pre-Installed Android SDKs
           remove-haskell: true          # Remove Haskell Tool Chains
           remove-codeql: true           # Remove CodeQL to Free Space
-
-      - name: 👤 Git Identity
-        shell: bash
-        run: |      
-          # Configure Git Identity if Not Already Set
-          if ! git config --global user.name >/dev/null; then
-            git config --global user.name "AndreiMikh"
-          fi
-          
-          if ! git config --global user.email >/dev/null; then
-            git config --global user.email "andreimikhail0088@gmail.com"
-          fi
-
-          # Prepare the Workspace Directory
-          mkdir -p "$WORKDIR" || {
-            echo "⚠️ Failed to Create Directory: $WORKDIR"
-            exit 1
-          }
-
-          # Clone Required Branch
-          echo "📥 Cloning Branch..."
-          git clone --depth=1 \
-            -b LiquidAndrei \
-            https://github.com/AndreiMikh/AndreiMikh-Kernel-Lab.git \
-            "$WORKDIR/AndreiMikh-Kernel-Lab"
-          echo "⚙️ Branch Cloned Successfully"
-          ls -la "$WORKDIR/AndreiMikh-Kernel-Lab"    
-          echo "🎉 Workspace Created and Git Configuration Applied:"
-          git config --global --list
 
       - name: 🧰 Build Dependencies
         shell: bash
