Update Test System V IPC.yml

diff --git a/.github/workflows/Test System V IPC.yml b/.github/workflows/Test System V IPC.yml
--- a/.github/workflows/Test System V IPC.yml
+++ b/.github/workflows/Test System V IPC.yml
@@ -3064,6 +3064,12 @@ jobs:
 
           # Navigate to Root Directory
           cd kernel_workspace/kernel_platform/common
+
+          # Check if Headers Exists Before Proceeding
+          if [[ ! -f "include/linux/sched.h" ]]; then
+            echo "⚠️ Headers Not Found, Exiting..."
+            exit 1
+          fi
     
           # Check and Modify the Original System V Struct Definitions
           echo "🔧 Modifying System V Struct Definitions..."
