Update Test NTSync.yml

diff --git a/.github/workflows/Test NTSync.yml b/.github/workflows/Test NTSync.yml
--- a/.github/workflows/Test NTSync.yml
+++ b/.github/workflows/Test NTSync.yml
@@ -2299,12 +2299,19 @@ jobs:
 
               echo "🔄 Looking for NTSync Patches for Kernel: $GKIVERSION"
 
-              # Determine Correct Compat File
+              # Define Patch Files and Source Directory
               COMPAT_PATCH="ntsync_compat_${GKIVERSION}.patch"
               BASE_PATCH="ntsync_base.patch"
               SRC_DIR="$GITHUB_WORKSPACE/kernel_workspace/WildKernels/common/ntsync"
 
-              # Check file existence
+              # Log Available Patches in Source Directory
+              echo "🔍 Available NTSync Patches in $SRC_DIR:"
+              ls "$SRC_DIR" || {
+                echo "⚠️ Failed to Fetch List of Patches in $SRC_DIR"
+                exit 1
+              }
+
+              # Check Compat Patch File Existence and Apply
               if [[ ! -f "$SRC_DIR/$COMPAT_PATCH" ]]; then
                 echo "⚠️ Compat Patch Not Found for $GKIVERSION — Skipped: $COMPAT_PATCH"
               else
@@ -2315,6 +2322,7 @@ jobs:
                 rm -f "$COMPAT_PATCH"
               fi
 
+              # Check Base Patch File Existence and Apply
               if [[ ! -f "$SRC_DIR/$BASE_PATCH" ]]; then
                 echo "⚠️ Base Patch Missing: $BASE_PATCH"
               else
