Update Test.yml

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -2929,7 +2929,61 @@ jobs:
           # ------------------------------
           echo ">> Compiler Cache Statistics"
           ccache -s
-          
+
+      - name: Fallback to Build Kernel
+        if: ${{ github.event.inputs.FAST_BUILD == 'false' || steps.fast_build.outputs.fallback == 'true' }}
+        run: |
+          set -Eeuo pipefail
+
+          cd kernel_workspace
+
+          CPU="${{ env.CPUD }}"
+          METHOD="${{ env.BUILD_METHOD }}"
+
+          echo "======= Kernel Build ======="
+          echo "CPU: $CPU"
+          echo "Method: $METHOD"
+          echo "============================"
+
+          BAZEL_SCRIPT="./kernel_platform/build_with_bazel.py"
+          OPLUS_SCRIPT="./kernel_platform/oplus/build/oplus_build_kernel.sh"
+
+          # Default Build Flags
+          export LTO=${LTO:-thin}
+          export SYSTEM_DLKM_RE_SIGN=${SYSTEM_DLKM_RE_SIGN:-0}
+          export BUILD_SYSTEM_DLKM=${BUILD_SYSTEM_DLKM:-0}
+          export KMI_SYMBOL_LIST_STRICT_MODE=${KMI_SYMBOL_LIST_STRICT_MODE:-0}
+
+          # -----------------------------
+          # Detect Build System
+          # -----------------------------
+          if [[ -f "$BAZEL_SCRIPT" ]]; then
+
+            echo "Detected Bazel / KLeaf Build System"
+
+            ./kernel_platform/oplus/bazel/oplus_modules_variant.sh "$CPU" "$METHOD"
+
+            python3 "$BAZEL_SCRIPT" \
+              -t "$CPU" \
+              "$METHOD"
+
+          elif [[ -f "$OPLUS_SCRIPT" ]]; then
+
+            echo "Detected Legacy OPlus Build System"
+
+            "$OPLUS_SCRIPT" \
+              "$CPU" \
+              "$METHOD"
+
+          else
+
+            echo "⚠️ ERROR: No Valid Build System Found"
+            exit 1
+
+          fi
+
+          echo "-------- Build Done --------"
+    
       # ==============================
       # Save Compiler Cache 
       # ==============================
